### PR TITLE
[Helm] Update check for unsupportedKubernetesVersion

### PR DESCRIPTION
**Pull request by atsai1220**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Helm template for `unsupportedKubernetesVersion` is `nil` if Kubernetes version check passes successfully in `cloud-provider-azure.yaml` (the variable `cloudProviderAzureVersion` is set then `unsupportedKubernetesVersion` is not set).

We receive this error:
```
template: cloud-provider-az/templates/_image.tpl:7:16: executing "image.cloudControllerManager" at <eq .unsupportedKubernetesVersion "true">: error calling eq: incompatible types for comparison]
```

#### Special notes for your reviewer:
Thank you :) 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[Helm]: https://helm.sh/docs/chart_template_guide/control_structures/#ifelse
```

This is a recreation of https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2466

### CODE REVIEW

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by jackfrancis** [comment]
/hold

If you don't mind, @atsai1220, let's include this change in the next version of the Chart

Our CI is blocking on the fact that we are updating the chart but not cutting a new version. There's a good reason to keep that CI in place (it ensures we don't have a delta between our Chart specification and the published versions that folks are using).

**Comment by atsai1220** [comment]
> /hold
> 
> If you don't mind, @atsai1220, let's include this change in the next version of the Chart
> 
> Our CI is blocking on the fact that we are updating the chart but not cutting a new version. There's a good reason to keep that CI in place (it ensures we don't have a delta between our Chart specification and the published versions that folks are using).

Sounds good. Is there anything I can help with for the next version of the Chart?

**Comment by atsai1220** [comment]
Closing this in favor of: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/2602

**Pull request closed without merging**
