### PR TITLE
Tests: e2e add multiport service test

### LINKED ISSUE #1318: test: add e2e tests for LoadBalancer service with multiple ports and local external traffic policy
Followup for https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1317: 

We should add e2e tests for the following steps:

* create LoadBalancer service with multiple ports and local external traffic policy, and validate the connectivity for all the ports.
* change the external traffic policy from local to cluster, and validate lb rules and probe rules, also validate the connectivity
* change the external traffic policy from cluster to local, and validate lb rules and probe rules, also validate the connectivity

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?

/kind testing

#### What this PR does / why we need it:

We need to add e2e test case to cover the scenario in which a service with multiple ports is applied. 
 
#### Which issue(s) this PR fixes:

Fixes #1318

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
/test 
pull-cloud-provider-azure-e2e-ccm-capz

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
