### PR TITLE
test only

### PR DESCRIPTION
**Pull request by nilo19**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
@nojnhuh seems the workload cluster cannot be created.

**Comment by nojnhuh** [comment]
There are some region-specific issues we're seeing that should be addressed by https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5003. Jobs may be flaky until then. 

/retest

**Comment by nojnhuh** [comment]
I think the reason the CAPZ 1.16 job is failing is because the job is using a template from CAPZ's 1.15 branch. I have a PR open to update the template here: https://github.com/kubernetes/test-infra/pull/33057

**Comment by nilo19** [comment]
need to wait for a couple of min to let it take effect

**Comment by nojnhuh** [comment]
Looks like the cluster came up fine this time but then all the Azure resources start getting deleted out from underneath CAPZ. I'm curious to see if this happens again...

/test pull-cloud-provider-azure-e2e-ccm-vmss-capz-eks-test

**Comment by nilo19** [comment]
E0725 01:24:49.050650       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 329 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x269e300, 0x479fde0})
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0008b4380?})
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x269e300?, 0x479fde0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).getRouteTable(0xb0d7da95cbcfe?, 0x6?)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets_repo.go:184 +0x4f
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).ListRoutes(0xc0006c2008, {0x410130?, 0xc000844e78?}, {0x7fff3dee6af1, 0xb})
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go:283 +0x145
k8s.io/cloud-provider/controllers/route.(*RouteController).reconcileNodeRoutes(0xc0002e9100, {0x303f160, 0x4858a00})
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:128 +0x42
k8s.io/cloud-provider/controllers/route.(*RouteController).Run.func1()
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:119 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0008ac8a0?)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000864ec0, {0x30019e0, 0xc0008ac8a0}, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000864ec0, 0x2540be400, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntil(...)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:180
created by k8s.io/cloud-provider/controllers/route.(*RouteController).Run in goroutine 243
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:118 +0x45d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x22ebcaf]

goroutine 329 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0008b4380?})
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x269e300?, 0x479fde0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).getRouteTable(0xb0d7da95cbcfe?, 0x6?)
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets_repo.go:184 +0x4f
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).ListRoutes(0xc0006c2008, {0x410130?, 0xc000844e78?}, {0x7fff3dee6af1, 0xb})
	/go/src/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go:283 +0x145
k8s.io/cloud-provider/controllers/route.(*RouteController).reconcileNodeRoutes(0xc0002e9100, {0x303f160, 0x4858a00})
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:128 +0x42
k8s.io/cloud-provider/controllers/route.(*RouteController).Run.func1()
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:119 +0x25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0008ac8a0?)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000864ec0, {0x30019e0, 0xc0008ac8a0}, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000864ec0, 0x2540be400, 0x0, 0x0, 0x0)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntil(...)
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:180
created by k8s.io/cloud-provider/controllers/route.(*RouteController).Run in goroutine 243
	/go/src/sigs.k8s.io/cloud-provider-azure/vendor/k8s.io/cloud-provider/controllers/route/route_controller.go:118 +0x45d

**Comment by nilo19** [comment]
It seems the federated identity token file env is not set, so [this code](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/tests/e2e/utils/azure_auth.go#L71) is not hit.
It returned early [here](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure.go#L695), causing the route cache to be nil.

**Comment by jsturtevant** [comment]
It looks like the [ENV is there](https://prow.k8s.io/prowjob?prowjob=0271168a-7fe6-435e-a0f5-3caf46c37d2d):

      - name: AZURE_FEDERATED_TOKEN_FILE
        value: /var/run/secrets/azure-token/serviceaccount/token

**Comment by nojnhuh** [comment]
CAPZ will use workload identity to authenticate to Azure from the CAPI management cluster, but then we configure cloud-provider to authenticate with a user assigned identity assigned to the nodes of the workload cluster.

I see this in the cloud-controller-manager logs:
```
I0725 01:24:38.945226       1 azure_auth.go:316] Using AzurePublicCloud environment
I0725 01:24:38.945321       1 azure_auth.go:169] "No valid auth method found" logger="GetServicePrincipalToken"
I0725 01:24:38.945380       1 azure.go:689] Azure cloud provider is starting without credentials
```

In the VMSS test we run in CAPZ, the logs look more like what I would expect to see (from [this run](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-cluster-api-provider-azure-e2e/1816265001099333632)):
```
I0725 00:32:26.813238       1 azure_auth.go:313] Using AzurePublicCloud environment
I0725 00:32:26.813624       1 azure_auth.go:106] "Setup ARM general resource token provider" logger="GetServicePrincipalToken" method="msi"
I0725 00:32:26.813743       1 azure_auth.go:112] "Parsing user assigned managed identity" logger="GetServicePrincipalToken"
I0725 00:32:26.813865       1 azure_auth.go:123] "Setup with user assigned managed identity" logger="GetServicePrincipalToken" id-type="client_id"
```

I'm not exactly sure what would cause that difference in this case based on a quick look at the templates. Tomorrow I can try spinning up an instance of the specific template being used here to see if the azure.json looks right on the node and cloud-provider can find credentials.

**Comment by nojnhuh** [comment]
Spinning up an instance of the template locally, this is what the azure.json should look like based on the secret generated by CAPZ, which looks correct to me and shouldn't be resulting in those `No valid auth method found` log messages:
```json
{
    "cloud": "AzurePublicCloud",
    "tenantId": "<tenant>",
    "subscriptionId": "<sub>",
    "resourceGroup": "prow-machine-pool-ci-version-3075",
    "securityGroupName": "prow-machine-pool-ci-version-3075-node-nsg",
    "securityGroupResourceGroup": "prow-machine-pool-ci-version-3075",
    "location": "westus2",
    "vmType": "vmss",
    "vnetName": "prow-machine-pool-ci-version-3075-vnet",
    "vnetResourceGroup": "prow-machine-pool-ci-version-3075",
    "subnetName": "node-subnet",
    "routeTableName": "prow-machine-pool-ci-version-3075-node-routetable",
    "loadBalancerSku": "Standard",
    "loadBalancerName": "",
    "maximumLoadBalancerRuleCount": 250,
    "useManagedIdentityExtension": true,
    "useInstanceMetadata": true,
    "enableVmssFlexNodes": true,
    "userAssignedIdentityID": "<managed identity client ID>"
}
```

I'll kick off another test and log into the node to see what's actually there.

/test pull-cloud-provider-azure-e2e-ccm-vmss-capz-eks-test

**Comment by nojnhuh** [comment]
@jsturtevant Found that ci-entrypoint jobs by default override the azure.json generated by CAPZ normally with a custom static file that is only configured for service principal auth, so we're updating the default in CAPZ's main branch to one using managed identity in this PR: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5023. Once that merges we can rerun the test.

**Comment by jsturtevant** [comment]
It looks like most of the tests are passing at this point.  

I do see one failure: 


```
Azure Credential Provider [It] should be able to create an ACR cache and pull images from it [Credential]
[2307](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/6638/pull-cloud-provider-azure-e2e-ccm-vmss-capz-eks-test/1816593076194381824#1:build-log.txt%3A2307)
/home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/auth/cred.go:94
```

This looks to be easily remedied by updating the login here to support federated login (or use the go sdk directly):

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/tests/e2e/utils/container_registry_utils.go#L92-L98

**Comment by jsturtevant** [comment]
Scanning the code I believe this will need to be updated as well: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/54202e6df4252fa3a52985c57a083ec3278b4e45/tests/kubemark/build-kubemark.sh#L124

**Comment by nojnhuh** [comment]
> (or use the go sdk directly):

Using all the defaults with the SDK like this worked for both service principal and workload identity without any changes in CAPZ's e2e tests. That should work for both here too since it only relies on environment variables that are already set on the job.

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/1b40a1ab6ac025dd328ca22ca71ad4272e27cf94/test/e2e/aks_tags.go#L49

**Comment by nojnhuh** [comment]
There's also this failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/6638/pull-cloud-provider-azure-e2e-ccm-vmss-capz-eks-test/1816593076194381824#1:build-log.txt%3A4974-4987
```
Jul 26 00:58:37.376: INFO: tags: [a:b c:d e: DateCreated:07/26/2024 ] [/home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/service_annotations.go:1424]
Jul 26 00:58:37.376: INFO: expectedTags: [a:b c:d e: ] [/home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/service_annotations.go:1424] 
...
 • [FAILED] [1560.125 seconds]
Service with annotation [It] should support service annotation `service.beta.kubernetes.io/azure-pip-tags` [ServiceAnnotation]
/home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/service_annotations.go:459
  [FAILED] Unexpected error:
      <wait.errInterrupted>: 
      timed out waiting for the condition
      {
          cause: <*errors.errorString | 0xc0002fa2a0>{
              s: "timed out waiting for the condition",
          },
      }
  occurred
  In [It] at: /home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/service_annotations.go:1717 @ 07/26/24 01:22:53.744 
```
We discovered that the new subscription has an Azure Policy applied to all resources in the sub that adds this `DateCreated` tag automatically, so the test will need to account for that.

**Comment by nojnhuh** [comment]
It looks like the tag policy is what's causing the "should support BYO public IP" also test to fail. All other tests passed!

**Comment by nojnhuh** [comment]
@nilo19 I have a PR open that shows one way to fix the "should be able to create an ACR cache and pull images from it" test: #6675. Feel free to merge that or use it as a starting point for a new PR. It looks like you have a handle on the other failures in #6673.

**Pull request closed without merging**
