### PR TITLE
feat: Provide IPv6 support for internal load balancer

### LINKED ISSUE #697: feat: remove the ipv6 check on ILB
**Is your feature request related to a problem? Please describe.**

ipv6 on ILB would report an error because of the following check:

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/f8cb009de8b8479baa03343308ed88d434a98131/pkg/provider/azure_loadbalancer.go#L1785-L1790

The check should be removed because ipv6 has been supported now on ILB.

**Describe the solution you'd like in detail**

Validate and remove the ipv6 check on ILB.

**Describe alternatives you've considered**

**Additional context**

The changes should also be cherry-picked to k/k.

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: GitHub <noreply@github.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #697

**Special notes for your reviewer**:

I'm happy to help further but I'm new to Go. I have tried to check the SDK version but from what I've heard it should be fine.

**Release note**:
```
Feat: Provide IPv6 support for internal load balancer
```

### CODE REVIEW

**Comment by nilo19** [comment]
@tomkerkhove do you test it by creating an internal ipv6 lb typed service?

**Comment by tomkerkhove** [comment]
We need to use this with AKS-Engine but have not tested this because I'm new to Go.
Is there guidance on how to test this? I'm happy to do so!

**Review by aramase — COMMENTED** [review]
Thank you for the PR! I did some validation and there is one additional change required on top of removing this check. I've the changes here: https://github.com/kubernetes-sigs/cloud-provider-azure/compare/master...aramase:ipv6-ilb?expand=1. Please take a look and include those as part of your PR.

1. With the current cloud-controller-manager
```yaml
➜ k describe svc nginx-ipv6-ilb
Name:                     nginx-ipv6-ilb
Namespace:                default
Labels:                   app=nginx
Annotations:              service.beta.kubernetes.io/azure-load-balancer-internal: true
Selector:                 app=nginx
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv6
IP:                       fd00::f488
IPs:                      fd00::f488
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  31468/TCP
Endpoints:                [fc00::6]:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age              From                Message
  ----     ------                  ----             ----                -------
  Normal   EnsuringLoadBalancer    1s (x2 over 6s)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  1s (x2 over 6s)  service-controller  Error syncing load balancer: failed to ensure load balancer: ensure(default/nginx-ipv6-ilb): lb(ds0716-internal) - internal load balancers does not support IPv6
```

2. With the changes from my branch
```yaml
➜ k describe svc nginx-ipv6-ilb
Name:                     nginx-ipv6-ilb
Namespace:                default
Labels:                   app=nginx
Annotations:              service.beta.kubernetes.io/azure-load-balancer-internal: true
Selector:                 app=nginx
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv6
IP:                       fd00::b523
IPs:                      fd00::b523
LoadBalancer Ingress:     2001:1234:5678:9abc::6
Port:                     <unset>  80/TCP
TargetPort:               80/TCP
NodePort:                 <unset>  32400/TCP
Endpoints:                [fc00::7]:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  52m   service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   51m   service-controller  Ensured load balancer
```

**Comment by tomkerkhove** [comment]
Certainly, I'll make the changes tomorrow!

**Comment by tomkerkhove** [comment]
Makes a lot of sense, thanks for suggesting @aramase!

**Comment by tomkerkhove** [comment]
Did a force push because of invalid commit message - Sorry about that.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by feiskyer** [comment]
I merged this without tests since there're urgent asks for this. @nilo19 let's cherry-pick this to old releases and k/k repo.

**Comment by tomkerkhove** [comment]
Thank you for merging, let me know if I can help any further!

**Pull request merged**
