### PR TITLE
Fix checking service references from `tags` when deleting PIP

### LINKED ISSUE #7130: Create AKS cluster with `--tags service=` would prevent the cloud provider from deleting the PublicIP
#### What happened:

When creating AKS cluster with `--tags service=foo`, it would prevent the cloud provider from deleting the Public IP of service.

#### What you expected to happen:

The cleanup of PublicIP will not be affected even if the tag is set.

#### How to reproduce it (as minimally and precisely as possible):

``` bash
az aks create -g $RG -n $CLUSTER --tags service=foo
az aks get-credential -g $RG -n $CLUSTER

k apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  type: LoadBalancer
  selector:
    app: foo
  ports:
    - name: tcp
      port: 4000
      protocol: TCP
      targetPort: 4000
EOF

# wait a few seconds until the PublicIP is created
```

image

``` bash
# then delete the service
k delete svc foo
```

image

The Public IP is not deleted.

#### Anything else we need to know?:

If we add the tag `service=foo` after the cluster and Public IP are created, the cleanup works as expected. It seems to only be impacted when the cluster is created with the tag.

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by zarvd**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #7130 

#### Special notes for your reviewer:

Also, this PR deletes some obsolete, unused code.

#### Does this PR introduce a user-facing change?

```release-note
Fix checking service references from `tags` when deleting PIP
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feiskyer** [comment]
Could you fix the unit tests?

**Comment by nilo19** [comment]
Can we add an e2e for this? Don't forget to squash your commits before merging.

**Comment by zarvd** [comment]
> Can we add an e2e for this? Don't forget to squash your commits before merging.

It’s not a critical use case; I think we could skip the e2e test, given that the current e2e tests take too long to run.

**Comment by nilo19** [comment]
> > Can we add an e2e for this? Don't forget to squash your commits before merging.
> 
> It’s not a critical use case; I think we could skip the e2e test, given that the current e2e tests take too long to run.

Can we cover the change by changing this line?
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/tests/e2e/network/ensureloadbalancer.go#L169

**Review by feiskyer — COMMENTED** [review]
/approve

**Pull request merged**
