### PR TITLE
api-model: remove --service-account-issuer

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

With https://github.com/Azure/aks-engine/pull/4262, it should have the correct default value for the `--service-account-issuer` flag.

/kind failing-testing
/assign @feiskyer 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```

```

### CODE REVIEW

**Comment by feiskyer** [comment]
have the aks-engine version released and updated in test-infra jobs?

**Comment by chewong** [comment]
I will update the aks-engine version to nightly after this PR is merged

**Pull request merged**
