### PR TITLE
Add e2e test cases for multiple services sharing one ip address

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Add e2e test cases for multiple services sharing one ip address

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by nilo19** [comment]
would pass the test after https://github.com/kubernetes-sigs/cloud-provider-azure/pull/405#pullrequestreview-502860410 get merged.

**Comment by nilo19** [comment]
this would fail because the CI tests are using release-1.19 branch

**Comment by nilo19** [comment]
pip limit reached, will retry later

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
