### PR TITLE
[WIP][NOT FOR REVIEW] Improve test stability

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feiskyer** [comment]
@lzhecheng for draft PR, it is suggested to add "WIP" in the title, or just make a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

**Comment by lzhecheng** [comment]
This time all tests are successful. Will push to trigger again.

**Pull request closed without merging**
