### PR TITLE
linux-vmss-multi-zone template: enable TopologyAwareHints

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Enable TopologyAwareHints for linux-vmss-multi-zone template
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/ok-to-test

**Review by feiskyer — COMMENTED** [review]
/retest
/lgtm
/approve

**Comment by nilo19** [comment]
@lzhecheng I don't think we need to make a release note if there is no user-facing changes.

**Comment by feiskyer** [comment]
> @lzhecheng I don't think we need to make a release note if there are no user-facing changes.

Yes, that makes sense. I edited the release note to none now.

**Comment by lzhecheng** [comment]
@nilo19 @feiskyer Thank you! Will pay attention next time.

**Pull request merged**
