### PR TITLE
Consolidate adjacent CIDR ranges for allowed sources

### PR DESCRIPTION
**Pull request by zarvd**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

In #6807, we added a feature that groups overlapping CIDRs together. This PR takes it further by aggressively merging any adjacent CIDRs, reducing the total number of CIDRs in NSG.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Consolidate adjacent CIDR ranges for allowed sources
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zarvd** [comment]
We might also apply it to destination addresses to see if it helps with #5919. Will do that in the next PR.

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request merged**
