### PR TITLE
Simplify update-dependencies.sh

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
/hold
The code block being deleted is used for pinning versions. Not sure if it is still needed. @feiskyer

**Comment by lzhecheng** [comment]
@nilo19 we have an offline discussion on this and he agreed to remove it. But still let him take a look at the change.

**Review by feiskyer — APPROVED** [review]
Those steps are not required any more as we won't depend on the k/k directly now.

/ok-to-test
/lgtm
/hold cancel

**Pull request merged**
