### PR TITLE
feat: add DiskEncryptionType in CreateDisk

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
feat: add DiskEncryptionType in CreateDisk

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
feat: add DiskEncryptionType in CreateDisk
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
feat: add DiskEncryptionType in CreateDisk
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
chart config is broken, not related to this PR:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1646/pull-cloud-provider-azure-check/1521844201916993536
```
+ tar -xf hack/../helm/repo/cloud-provider-azure-1.23.10.tgz -C chart_verify
+ diff -r hack/../chart_verify/cloud-provider-azure/ hack/../helm/cloud-provider-azure/ --exclude README.md
diff -r --exclude README.md hack/../chart_verify/cloud-provider-azure/Chart.yaml hack/../helm/cloud-provider-azure/Chart.yaml
16c16
< version: 1.23.10
---
> version: 1.23.11
diff -r --exclude README.md hack/../chart_verify/cloud-provider-azure/values.yaml hack/../helm/cloud-provider-azure/values.yaml
17c17
<   # imageTag: "canary"
---
>   imageTag: "v1.23.11"
45c45
<   # imageTag: "canary"
---
>   imageTag: "v1.23.11"
+ exit 1
make: *** [Makefile:334: test-helm] Error 1
+ EXIT_VALUE=2
+ set +o xtrace
```

**Comment by jackfrancis** [comment]
@andyzhangx I can't repro the non-zero exit code when running `hack/verify-helm-repo.sh` locally.

```
$ git status
On branch DiskEncryptionType
Your branch is up to date with 'andyzhangx/DiskEncryptionType'.

nothing to commit, working tree clean
$ hack/verify-helm-repo.sh 
++ dirname hack/verify-helm-repo.sh
+ REPO_ROOT=hack/..
+ for chart in '"cloud-provider-azure"'
++ ls -t hack/../helm/repo/cloud-provider-azure-1.23.10.tgz hack/../helm/repo/cloud-provider-azure-1.23.11.tgz hack/../helm/repo/cloud-provider-azure-1.23.8.tgz
++ head -n 1
+ LATEST_CHART=hack/../helm/repo/cloud-provider-azure-1.23.11.tgz
++ echo hack/../helm/repo/cloud-provider-azure-1.23.11.tgz
++ grep -Eoq '[0-9]+.[0-9]+.[0-9]+'
+ LATEST_VERSION=
+ MATCH_STRING='version: '
+ grep -q 'version: ' hack/../helm/cloud-provider-azure/Chart.yaml
+ rm -Rf hack/../chart_verify
+ mkdir hack/../chart_verify
+ tar -xf hack/../helm/repo/cloud-provider-azure-1.23.11.tgz -C chart_verify
+ diff -r hack/../chart_verify/cloud-provider-azure/ hack/../helm/cloud-provider-azure/ --exclude README.md
+ rm -Rf hack/../chart_verify
+ exit 0
```

**Comment by MartinForReal** [comment]
please rebase this pr after https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1640 is merged. Thanks!

**Review by ZeroMagic — APPROVED** [review]
/lgtm

**Pull request merged**
