### PR TITLE
Add a toggle for AKS Cluster

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

#### What type of PR is this?
/kind testing

#### What this PR does / why we need it:
Add a toggle for AKS Cluster
Disable ccm e2e tests for aks cluster for now..

This is the first PR of https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1929
After this PR and its cherrypicks are merged, I will merge the azure pipeline PR. Then we can adjust e2e for aks clusters with pipeline set up.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
@lzhecheng why do you want to enable them one by one? Is it better to enable them at a time so we can have more knowledge of why they fail?

**Comment by lzhecheng** [comment]
> @lzhecheng why do you want to enable them one by one? Is it better to enable them at a time so we can have more knowledge of why they fail?

My intention is to let other developers to contribute to the aks cluster pipeline. With this PR and azure pipeline PR merged, developers can verify their PR with the whole pipeline.
To be clear, not enable them one by one but some by some. Maybe just 2-3 PRs enable them all. Usually, the follow-up PRs just need to adjust some e2e code since ccm is not visiable in aks cluster overlay.

**Comment by lzhecheng** [comment]
> > > @lzhecheng why do you want to enable them one by one? Is it better to enable them at a time so we can have more knowledge of why they fail?
> > 
> > 
> > My intention is to let other developers to contribute to the aks cluster pipeline. With this PR and azure pipeline PR merged, developers can verify their PR with the whole pipeline. To be clear, not enable them one by one but some by some. Maybe just 2-3 PRs enable them all. Usually, the follow-up PRs just need to adjust some e2e code since ccm is not visiable in aks cluster overlay.
> 
> Maybe we can use ginkgo label filter or focus string.

Good idea. Updated.

**Comment by nilo19** [comment]
Can you put the skipping label in the Describe nodes?

**Comment by lzhecheng** [comment]
> Can you put the skipping label in the Describe nodes?

Updated.

**Pull request merged**
