### PR TITLE
Hotfix: fix probe missing when external traffic is local with multiple port opened.

### PR DESCRIPTION
**Pull request by MartinForReal**
Signed-off-by: GitHub <noreply@github.com>

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug in health probe generator. Probe related configuration is not updated due to variable scope
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by 4c74356b41** [comment]
hey, I'm a bit confused. which aks version this will be available with? i can see you are cherry picking to multiple different releases, but I don't really know what aks version they map to

**Comment by feiskyer** [comment]
@4c74356b41 see the version matrix https://github.com/kubernetes-sigs/cloud-provider-azure#current-status (AKS has enabled cloud-controller-manager for versions >=1.22.0)

**Comment by MartinForReal** [comment]
merge this commit because e2e tests have been executed for a few times

**Comment by 4c74356b41** [comment]
> @4c74356b41 see the version matrix https://github.com/kubernetes-sigs/cloud-provider-azure#current-status (AKS has enabled cloud-controller-manager for versions >=1.22.0)

this only gives part of the answer. so you are merging to 1.23 and 1.1, which corresponds to 1.22 and 1.23 k8s version, but which patch version is that? or when is it going to be available in aks? or what do i need to do to encorporate this fix?

**Comment by MartinForReal** [comment]
I will be rolled out to all aks regions

**Comment by 4c74356b41** [comment]
all patch versions? when? i assume if it gets retrofitted I'd just need to do smth like:
```
az aks upgrade --node-image-only
```
?

**Pull request merged**
