### PR TITLE
chore: upgrade deps to fix CVEs for release-0.7

### PR DESCRIPTION
**Pull request by luncj**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
upgrade deps to fix CVEs

before:
ccm-0
after:
ccm-1

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
chore: upgrade `github.com/gogo/protobuf` to v1.3.2, `golang.org/x/crypto` to v0.0.0-20220112180741-5e0467b6c7ce and `golang.org/x/text` to v0.3.7
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by luncj** [comment]
cc @mainred

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
