### PR TITLE
fix: update snapshotclient api version for Azure Stack

### PR DESCRIPTION
**Pull request by songjiaxun**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
/kind bug

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Update snapshotclient API version for Azure Stack

**Release note**:
```
none
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/ok-to-test

**Comment by andyzhangx** [comment]
@songjiaxun  we are going to release v1.0.0 azure disk driver very soon, do you want this PR get merged before release?

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
