### PR TITLE
build: auto generate release note for site

### LINKED ISSUE #1025: Publish release notes to the doc website automatically by github actions
#### What would you like to be added:

Release notes on the website: https://kubernetes-sigs.github.io/cloud-provider-azure/blog/
Corresponding files: site/content/en/blog/releases/*.md

### PR DESCRIPTION
**Pull request by lodrem**
#### Which issue(s) this PR fixes:

Fixes #1025

Flow:
1. push new release tag
2. github action triggered
    1. create a release note and publish [sample](https://github.com/lodrem/cloud-provider-azure/releases/tag/untagged-ec6b2cfc0964addf98d8)
    2. create a PR to update site doc [sample](https://github.com/lodrem/cloud-provider-azure/pull/15)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
Is it possible to attach the PR hyperlinks after the PR number?

**Comment by lodrem** [comment]
> Is it possible to add the PR hyperlinks after the PR number?

sure. added.

**Pull request merged**
