### PR TITLE
Refactor: remove controllercommon in cloud and move configAzureClients out of configureMultiTenantClients

### PR DESCRIPTION
**Pull request by MartinForReal**
…

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
 remove controllercommon in cloud and move configAzureClients out of configureMultiTenantClients
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
<html>
<body>

/test pull-cloud-provider-azure-e2e-capz
--


<br class="Apple-interchange-newline">
</body>
</html>

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
