### PR TITLE
Refactor:move nsg related code to securitygroup package

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Refactor: move nsg related code to securitygroup package
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
/hold 
based on #7243

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by zarvd** [comment]
For "sigs.k8s.io/cloud-provider-azure/pkg/util/collectionutil", I would prefer `fnutil` as it contains the functional operations instead of pure collection ops.

**Pull request merged**
