### PR TITLE
WIP: Only exclude a node from Balancer when it has exclude label

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind bug

**What this PR does / why we need it**:

Only exclude a node from Balancer when it has exclude label or it is unmanaged.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/97467

**Special notes for your reviewer**:

**Release note**:
```
Only exclude a node from Balancer when it has exclude label
```

### CODE REVIEW

**Comment by feiskyer** [comment]
/cc @staebler @nilo19 

Pending verification on scenario https://github.com/kubernetes/kubernetes/issues/97467.

**Comment by wking** [comment]
I'm a bit fuzzy here, but openshift/kubernetes#499 is [passing our Azure CI][1] with just #443 and #448.  Are you interested in how our CI works with #443 and this PR?  Just this PR on top of our otherwise vanilla 1.20 cloud-provider?  Some other mixture?

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/499/pull-ci-openshift-kubernetes-master-e2e-azure/1341778311856001024

**Comment by nilo19** [comment]
yeah I think #448 is enough to fix this?

**Comment by feiskyer** [comment]
This PR is fixing a different issue from #448:

 * #448 is for not reporting errors with standalone VMs
 * #449 is for only excluding VMs from LB that have exclude labels

**Comment by feiskyer** [comment]
seems it doesn't work as expected. need more details how to reproduce https://github.com/kubernetes/kubernetes/issues/97467.

**Pull request closed without merging**
