### PR TITLE
Skip standalone VM when reconciling LoadBalancer

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind bug

**What this PR does / why we need it**:

Skip standalone VM when reconciling LoadBalancer as there is no availabilitySet for those VMs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
Skip standalone VM when reconciling LoadBalancer
```

### CODE REVIEW

**Comment by feiskyer** [comment]
cc @staebler @wking

**Comment by wking** [comment]
openshift/kubernetes#499 is [passing our Azure CI][1] with #443 and #448 on top of our otherwise vanilla 1.20 cloud-provider.  I'm not sure how #449 fits into this effort.  Is that expected to be in addition to this PR, or is it an orthogonal effort that would replace this PR?

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/499/pull-ci-openshift-kubernetes-master-e2e-azure/1341778311856001024

**Comment by nilo19** [comment]
@wking if you could confirm the issue has been resolved with #443 and #448, I would reopen https://github.com/kubernetes/kubernetes/pull/97455 and cherry-pick #448 to k/k as well.

**Pull request merged**
