### PR TITLE
fix: Fix ListByResourceGroup in azure diskClient mock

### PR DESCRIPTION
**Pull request by nearora-msft**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Rectify ListByResourceGroup mock so that UTs work as expected

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Comment by nilo19** [comment]
@nearora-msft thanks for the fix, would mirror it to the kubernetes repo later.

**Comment by nilo19** [comment]
`ERROR: server message: insufficient_scope: authorization failed`
@andyzhangx

**Comment by nearora-msft** [comment]
@nilo19 PR for mirroring to kubernetes repo : https://github.com/kubernetes/kubernetes/pull/97307

**Pull request merged**
