### PR TITLE
Introduce otel trace and metrics

### LINKED ISSUE #6603: Metrics for EnsureLB labeled with annotation and spec
#### What would you like to be added:

Latency / RPS / Success rate / more for service mutation labeled with annotation and/or spec.

#### Why is this needed:

It seems unable to measure the mutation of services when they are configured with annotations or spec controlled by the cloud provider.

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/c4822cf50a7e83d03b619240a4abee34603e7375/pkg/provider/azure_loadbalancer.go#L208-L225

### PR DESCRIPTION
**Pull request by zarvd**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

1. OTEL trace is still in progress and currently returns a noop tracer. Will have another PR soon to configure it.
2. Add a new metrics API endpoint `/metrics/v2` for the newer OTEL metrics to avoid disrupting the current metrics collection. This will replace the `/metrics` handler once stability is confirmed.
3. The new metrics for reconciling load balancer operations will include feature labels.
<details>

<summary>GET /metrics/v2</summary>

```
# HELP otel_scope_info Instrumentation Scope metadata
# TYPE otel_scope_info gauge
otel_scope_info{otel_scope_name="cloud-provider-azure",otel_scope_version=""} 1
# HELP promhttp_metric_handler_requests_in_flight Current number of scrapes being served.
# TYPE promhttp_metric_handler_requests_in_flight gauge
promhttp_metric_handler_requests_in_flight 1
# HELP promhttp_metric_handler_requests_total Total number of scrapes by HTTP status code.
# TYPE promhttp_metric_handler_requests_total counter
promhttp_metric_handler_requests_total{code="200"} 1
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
# HELP provider_reconcile_duration_seconds Measures the duration of reconcile operations in seconds.
# TYPE provider_reconcile_duration_seconds histogram
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="0.1"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="0.2"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="0.5"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="1"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="5"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="10"} 1
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="60"} 1
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="300"} 1
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="600"} 1
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true",le="+Inf"} 1
provider_reconcile_duration_seconds_sum{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true"} 7.265563324
provider_reconcile_duration_seconds_count{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="true"} 1
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="0.1"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="0.2"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="0.5"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="1"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="5"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="10"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="60"} 1
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="300"} 1
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="600"} 1
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="+Inf"} 1
provider_reconcile_duration_seconds_sum{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false"} 31.527305848
provider_reconcile_duration_seconds_count{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="false",annotations_allowed_service_tags="false",annotations_internal_load_balancer="true",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false"} 1
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="0.1"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="0.2"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="0.5"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="1"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="5"} 0
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="10"} 3
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="60"} 3
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="300"} 3
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="600"} 3
provider_reconcile_duration_seconds_bucket{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false",le="+Inf"} 3
provider_reconcile_duration_seconds_sum{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false"} 20.232701783
provider_reconcile_duration_seconds_count{annotations_additional_public_ips="false",annotations_allowed_ip_ranges="true",annotations_allowed_service_tags="false",annotations_internal_load_balancer="false",annotations_load_balancer_source_ranges="false",annotations_pip_name="false",annotations_pip_prefix="false",name="EnsureLoadBalancer",otel_scope_name="cloud-provider-azure",otel_scope_version="",spec_load_balancer_source_ranges="false"} 3
# HELP target_info Target metadata
# TYPE target_info gauge
target_info{service_name="unknown_service:cloud-controller-manager",telemetry_sdk_language="go",telemetry_sdk_name="opentelemetry",telemetry_sdk_version="1.28.0"} 1
```

</details>

#### Which issue(s) this PR fixes:

Fixes #6603

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zarvd** [comment]
just rebased again and it requires re-approval. thanks

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by zarvd** [comment]
rebased

**Pull request merged**
