### PR TITLE
Duplicate annotation.md

### PR DESCRIPTION
**Pull request by braieralves**
Duplicate annotation: "service.beta.kubernetes.io/service.beta.kubernetes.io/azure-disable-load-balancer-floating-ip"

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by quillanogle** [comment]
#sign-off

**Comment by MartinForReal** [comment]
@braieralves Could you please fix the spelling error? Thanks!

**Comment by braieralves** [comment]
Hello, @MartinForReal .
Sorry but this spelling error doesn't came from my PR.

image


Looks like this came from https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5225

What should i do, please?

Thank you

**Comment by MartinForReal** [comment]
@nilo19 Could you please fix the spelling error? Thanks!

**Comment by nilo19** [comment]
@braieralves can you help fix the typos reported by CI test in your PR? Thanks.

**Comment by braieralves** [comment]
Hello, @nilo19 
To be honest, i don't know why this error is being reported in my PR.

But this error is about this word:
image

Maybe you can change this word to the correct suggestion?
 https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5225

**Comment by nilo19** [comment]
@braieralves that's not relevant to your change, just because your PR is also about fixing a typo so I asked if you are willing to fix another one. I will file a PR to fix this. Thanks anyway.

**Comment by braieralves** [comment]
@nilo19 .
I don't care to fix any other error :)

My point is, i didn't find where to do this.

Thank you

**Pull request closed without merging**
