### PR TITLE
fix: PrivateEndpoint matching in storage account search

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixed two issues related to private endpoint:
 - fixed PrivateEndpoint matching in storage account search
 - fixed private dns zone creation error if it already exists, related error msg is like following:
```
E0720 08:55:58.712928       1 utils.go:123] GRPC error: rpc error: code = Internal desc = failed to ensure storage account: Failed to create private DNS zone(privatelink.file.core.windows.net) in resourceGroup(mc_andy-aks1205_andy-aks1205_eastus2), error: Code="PreconditionFailed" Message="The Zone privatelink.file.core.windows.net exists already and hence cannot be created again."
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/hold

**Release note**:
```
fixed PrivateEndpoint matching in storage account search
fixed private dns zone creation error if it already exists
```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
Looks good. Could you add some unit tests for the changes?

**Comment by andyzhangx** [comment]
> Looks good. Could you add some unit tests for the changes?

@feiskyer ut added, could you approve? thanks.

**Review by ZeroMagic — APPROVED** [review]
/lgtm

**Pull request merged**
