### PR TITLE
Allow external service with floating ip disabled to use PLS

### PR DESCRIPTION
**Pull request by jwtty**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Allow external service with floating ip disabled to create PLS.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Allow external service with floating ip disabled to create PLS.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feiskyer** [comment]
Also update document https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/#restrictions and add the unsupported limitation of "ELB+FloatingIP"?

**Comment by jwtty** [comment]
> Also update document https://cloud-provider-azure.sigs.k8s.io/topics/pls-integration/#restrictions and add the unsupported limitation of "ELB+FloatingIP"?

yes, I have another PR to update the doc.

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
