### PR TITLE
Track2 sdk:add etag support in network resources

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Track2 sdk:add etag support in network resources
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mainred** [comment]
Could you please share the steps in you did to add etags, in case I would add etags for nrp resources in the future.

**Comment by MartinForReal** [comment]
add etag=true in interface and run make generate

**Comment by mainred** [comment]
> add etag=true in interface and run make generate

@MartinForReal these only generate clients, may I ask how testdata is modified?

**Comment by MartinForReal** [comment]
export AZURE_SUBSCRIPTION_ID and AZURE_TENANT_ID
run az login 
and run go test ./...

**Pull request merged**
