### PR TITLE
Fix e2e tests to work with CAPZ

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Made some changes to get the CCM test suite to pass with a CAPZ built clusters. Tested using the `pull-cloud-provider-azure-e2e-ccm-capz` job.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
@feiskyer @nilo19 @chewong this is ready for review

**Comment by CecileRobertMichon** [comment]
/test pull-cloud-provider-azure-e2e-ccm-capz

success 2/2

**Review by feiskyer — COMMENTED** [review]
Thanks for making it works now.

/lgtm
/approve

**Pull request merged**
