### PR TITLE
Upgrade docker/dockerfile image

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Upgrade docker/dockerfile image
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lzhecheng** [comment]
@nilo19 tests are successful. Shall we merge it?

**Review by feiskyer — COMMENTED** [review]
Thanks for the upgrading

/lgtm
/approve

**Pull request merged**
