### PR TITLE
test: Add e2e tests for private link service integration

### PR DESCRIPTION
**Pull request by jwtty**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Add e2e tests for private link service integration
#### Which issue(s) this PR fixes:

Fixes #
related: #872 #1484
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
still failed due to 404

**Comment by jwtty** [comment]
> still failed due to 404

It's not a PLS e2e test. Should be transient. Retesting.

/test pull-cloud-provider-azure-e2e-ccm-capz

**Pull request merged**
