### PR TITLE
Bumps azclient to latest version

### LINKED ISSUE #5558: Failure to initialize on Azure Stack for v1.29
#### What happened:
On Azure StackHub initialization of the cloud provider fails: 
```
I0126 09:40:31.744654       1 leaderelection.go:281] successfully renewed lease openshift-cloud-controller-manager/cloud-controller-manager
I0126 09:40:36.766965       1 azure.go:931] Azure cloudprovider using try backoff: retries=6, exponent=1.500000, duration=6, jitter=1.000000
I0126 09:40:36.767030       1 azure_auth.go:142] azure: using client_id+client_secret to retrieve access token
I0126 09:40:36.767115       1 azure_diskclient.go:68] Azure DisksClient using API version: 2019-03-01
I0126 09:40:36.767196       1 azure_blobclient.go:73] Azure BlobClient using API version: 2019-06-01
W0126 09:40:36.767226       1 azure_privateendpointclient.go:66] Azure Stack is not supported for Private Endpoint API
W0126 09:40:36.767239       1 azure_privatednszonegroupclient.go:66] Azure Stack is not supported for Private DNS Zone Group API
F0126 09:40:36.777509       1 controllermanager.go:314] Cloud provider azure could not be initialized: could not init cloud provider azure: provided Cloud field is missing Azure Resource Manager configuration
```

#### What you expected to happen:
The cloud-provider to succesfully initialize without an error

#### How to reproduce it (as minimally and precisely as possible):
Start a cluster on Azure Stack Hub using the 1.29 release code for the cloud provider.

cloud.conf (exposed `CLOUD_CONFIG`) : 
```json
{
	"cloud": "AzureStackCloud",
	"tenantId": "edd13307-68dc-48da-9ee2-2791182e571f",
	"aadClientId": "",
	"aadClientSecret": "",
	"aadClientCertPath": "",
	"aadClientCertPassword": "",
	"useManagedIdentityExtension": false,
	"userAssignedIdentityID": "",
	"subscriptionId": "de7e09c3-b59a-4c7d-9c77-439c11b92879",
	"resourceManagerEndpoint": "https://management.mtcazs.wwtatc.com/",
	"resourceGroup": "zhsun-ash-bv56k-rg",
	"location": "mtcazs",
	"vnetName": "zhsun-ash-bv56k-vnet",
	"vnetResourceGroup": "zhsun-ash-bv56k-rg",
	"subnetName": "zhsun-ash-bv56k-worker-subnet",
	"securityGroupName": "zhsun-ash-bv56k-nsg",
	"routeTableName": "zhsun-ash-bv56k-node-routetable",
	"vmType": "standard",
	"loadBalancerSku": "basic",
	"cloudProviderBackoff": true,
	"excludeMasterFromStandardLB": false,
	"cloudProviderBackoffDuration": 6,
	"putVMSSVMBatchSize": 0,
	"enableMigrateToIPBasedBackendPoolAPI": false
}
```

`endpoints.conf` (exposed through `AZURE_ENVIRONMENT_FILEPATH`):

```json
{
  "name": "HybridEnvironment",
  "managementPortalURL": "",
  "publishSettingsURL": "",
  "serviceManagementEndpoint": "",
  "resourceManagerEndpoint": "https://management.mtcazs.wwtatc.com/",
  "activeDirectoryEndpoint": "https://login.microsoftonline.com/",
  "galleryEndpoint": "https://providers.azs2.local:30016/",
  "keyVaultEndpoint": "https://vault.mtcazs.wwtatc.com/",
  "managedHSMEndpoint": "",
  "graphEndpoint": "https://graph.windows.net/",
  "serviceBusEndpoint": "",
  "batchManagementEndpoint": "",
  "microsoftGraphEndpoint": "",
  "storageEndpointSuffix": "mtcazs.wwtatc.com",
  "cosmosDBDNSSuffix": "",
  "mariaDBDNSSuffix": "",
  "mySqlDatabaseDNSSuffix": "",
  "postgresqlDatabaseDNSSuffix": "",
  "sqlDatabaseDNSSuffix": "",
  "trafficManagerDNSSuffix": "",
  "keyVaultDNSSuffix": "vault.mtcazs.wwtatc.com",
  "managedHSMDNSSuffix": "",
  "serviceBusEndpointSuffix": "",
  "serviceManagementVMDNSSuffix": "",
  "resourceManagerVMDNSSuffix": "",
  "containerRegistryDNSSuffix": "",
  "tokenAudience": "https://management.wwtatc.onmicrosoft.com/1d974a95-a89d-4009-9aee-8d17ddf1971d",
  "apiManagementHostNameSuffix": "",
  "synapseEndpointSuffix": "",
  "datalakeSuffix": "",
  "resourceIdentifiers": {
    "graph": "",
    "keyVault": "",
    "datalake": "",
    "batch": "",
    "operationalInsights": "",
    "ossRDBMS": "",
    "storage": "",
    "synapse": "",
    "serviceBus": "",
    "sqlDatabase": "",
    "cosmosDB": "",
    "managedHSM": "",
    "microsoftGraph": ""
  }
}
```

#### Anything else we need to know?:
This issue seems to only happen on 1.29. Using the exact same configuration on 1.28 this issue does not exist.

This seems to be related to [#5147](https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5147) which initializes a new clientFactory. It's only dependant appears to be https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5206. 

This change impacts the initialization process, where [`NewAuthProvider`](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/5f58491438e69892013166abe8a8d7a710a7616f/pkg/provider/azure.go#L701 ) and subsequently [`GetAzureCloudConfig`](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/azclient/cloud.go#L121-L131) are called, leading to a failure due to missing Azure Resource Manager configuration (`armConfig.ResourceManagerEndpoint`) in the returned json from the endpoint. When we return the config, it is missing the resource manager field, causing initialisation to fail.

```json
[
  {
    "portal": "https://portal.mtcazs.wwtatc.com/",
    "authentication": {
      "loginEndpoint": "https://login.microsoftonline.com/",
      "audiences": [
        "https://management.wwtatc.onmicrosoft.com/1d974a95-a89d-4009-9aee-8d17ddf1971d"
      ]
    },
    "graphAudience": "https://graph.windows.net/",
    "graph": "https://graph.windows.net/",
    "name": "AzureStack-User-1d974a95-a89d-4009-9aee-8d17ddf1971d",
    "suffixes": {
      "keyVaultDns": "vault.mtcazs.wwtatc.com",
      "storage": "mtcazs.wwtatc.com"
    },
    "gallery": "https://providers.azs2.local:30016/"
  }
]
```

We have tried unsetting the ResourceManagerEndpoint in order to build the config from env vars, so the code path follows [AzureCloudConfigOverrideFromEnv](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/azclient/cloud.go#L130). 

This was unsuccessful. Specifically, unsetting the ResourceManagerEndpoint in the cloud conf causes issues when calling [`ParseAzureEnvironment`](https://github.com/openshift/cloud-provider-azure/blob/494bc606e391dafd8be6964f51b74eebf1c77c32/pkg/provider/azure.go#L611)  as it bypasses the [`azureStackOverrides`](https://github.com/openshift/cloud-provider-azure/blob/master/pkg/provider/config/azure_auth.go#L256-L259.) function, which is only called when building the configuration from the endpoint. I'm unsure as to if this behaviour is intentional?

Either way, this leads to the failure in generating a [service principal token](https://github.com/openshift/cloud-provider-azure/blob/494bc606e391dafd8be6964f51b74eebf1c77c32/pkg/provider/azure.go#L666) due to an unset `env.ServiceManagementEndpoint`.

Updating the code to call `azureStackOverrides when building from environment, as well as unsetting the ResourcemanagerEndpoint field fixes the problem - but does not seem ideal. 

```
I0227 15:16:51.247173       1 azure_auth.go:257] Using AzureStackCloud environment
I0227 15:16:51.247316       1 azure.go:931] Azure cloudprovider using try backoff: retries=6, exponent=1.500000, duration=6, jitter=1.000000
I0227 15:16:51.247376       1 azure_auth.go:142] azure: using client_id+client_secret to retrieve access token
F0227 15:16:51.247394       1 controllermanager.go:314] Cloud provider azure could not be initialized: could not init cloud provider azure: parameter 'resource' cannot be empty
reason: Error
startedAt: "2024-02-27T15:13:47Z"
```

#### Environment:

- Kubernetes version (use `kubectl version`):
```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5+c84a6b8
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by theobarberbany**
#### What type of PR is this?
/kind cleanup

Version vump

#### What this PR does / why we need it:

Bumps sigs.k8s.io/pkg/azclient to the latest version. This is to include changes from https://github.com/kubernetes-sigs/cloud-provider-azure/pull/5643

#### Which issue(s) this PR fixes:

Fixes #5558

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Seems innocuous 
/lgtm

Curious to know why this is a separate go module, wonder if one of the maintainers can explain why the clients need this bump separately, any way to work around it? Perhaps with go workspaces to avoid the needed bump?

**Comment by theobarberbany** [comment]
```
{Unexpected error:
    <wait.errInterrupted>: 
    timed out waiting for the condition
    {
        cause: <*errors.errorString | 0xc000269a10>{
            s: "timed out waiting for the condition",
        },
    }
occurred failed [FAILED] Unexpected error:
    <wait.errInterrupted>: 
    timed out waiting for the condition
    {
        cause: <*errors.errorString | 0xc000269a10>{
            s: "timed out waiting for the condition",
        },
    }
occurred
In [It] at: /home/prow/go/src/sigs.k8s.io/cloud-provider-azure/tests/e2e/network/service_annotations.go:960 @ 03/13/24 12:40:51.061

}
```

Looks like there's a timeout - guessing it may be a flake or have something to do with the cloud being slow? Going to retry.

**Comment by MartinForReal** [comment]
The clients will be used in 4 branches. And we don't want to maintain 4 copies of azclient.

**Comment by JoelSpeed** [comment]
> The clients will be used in 4 branches. And we don't want to maintain 4 copies of azclient.

So the idea is that the client library will be able to be used across all supported versions of the CCM, but only actually maintained on the master branch? Gotcha

**Pull request merged**
