### PR TITLE
Provide single and multiple vmss templates

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Provide single and multiple vmss templates
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lzhecheng** [comment]
This change won't affect pull-cloud-provider-azure-e2e-ccm-vmss-capz test result because this test uses yaml file on master branch.

**Comment by feiskyer** [comment]
merge manually to unblock CIs. Let's address the multiple VMSS issues in the following PRs

**Pull request merged**
