### PR TITLE
cleanup: Use k8s utils pointer instead of Azure autorest/to

### PR DESCRIPTION
**Pull request by umagnus**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Use k8s utils pointer instead of Azure autorest/to

- to.FooPtr becomes pointer.Foo
- to.Foo becomes pointer.FooDeref with an appropriate default
- to.StringSlicePtr becomes &

to.StringMap and to.StringSlice has no functions in k8s utils so we add them as common function

#### Which issue(s) this PR fixes:

This is related to https://github.com/kubernetes/kubernetes/issues/112431 (but doesn’t fix it).

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@umagnus could you rebase? thanks.

**Comment by umagnus** [comment]
> @umagnus could you rebase? thanks.

It's rebased.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
