### PR TITLE
Chores: refactor armclient and add request decorator to CRUD functions

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Add request decorator to CRUD functions in armclient
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
putresources function is removed. and ratelimiter in putresourceasync is refactored. 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
<html>
<body>


/test pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by lzhecheng** [comment]
The coverage drops quite a bit (0.4%)... Is it possible to make up for it?

**Comment by MartinForReal** [comment]
It is because test cases TestPutResourcesInBatches is removed.
I'm refactoring CRUD functions and PutResourcesInBatches function would be deleted.

**Comment by MartinForReal** [comment]
<html>
<body>


/test pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by jwtty** [comment]
The pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb test failed due to missing aks-engine cri setting for kubernetes 1.24. I'll submit a fix PR.

**Comment by lzhecheng** [comment]
Could you force-push again to see if the basic-lb job is gone?

**Comment by MartinForReal** [comment]
updated

**Pull request merged**
