### PR TITLE
Update pls-integration.md

### PR DESCRIPTION
**Pull request by chasewilson**
Adds annotation to define the resource where PLS Resource will be created. Feature addition #4660 

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Documents newly released feature
#### Which issue(s) this PR fixes:

Fixes #
No PR fix. 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chasewilson** [comment]
@feiskyer @jwtty let me know if this isn't a good set up for the docs update and feel free to copy the content in your own PR if that's easier.

**Comment by jwtty** [comment]
@chasewilson please fix the typo and all other changes look good to me. Thanks for enriching the doc!

**Pull request merged**
