### PR TITLE
add encryption setting in storage account creation

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
add encryption setting in storage account creation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
add encryption setting in storage account creation
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
add encryption setting in storage account creation
```

### CODE REVIEW

**Comment by monianshouhou** [comment]
> /retest

Sorry for that you have to use this following comment to rerun the failing azure pipeline test: 

/azp run kubernetes-sigs.cloud-provider-azure.basic_lb

We will try to supplement some prompts about the rerunning command later.

**Review by ZeroMagic — APPROVED** [review]
/lgtm

**Pull request merged**
