### PR TITLE
fix: set ForceAttemptHTTP2 to increase ARM throttling limit

### PR DESCRIPTION
**Pull request by umagnus**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
set ForceAttemptHTTP2 as false to respect custom dialer, after setting as false, the RoleInstance distribution is balanced a lot, this could also reduce ARM/VMSS throttling since ARM RoleInstance handling is distributed.

```
While HTTP/2 has many advantages abstractly, we have not been able to put in in mainline use in the control plane so far primarily because it doesn’t mesh well with the load-balanced architecture. You’d have to invest quite a bit in connection health and load-balancing management on the client side to get the robustness of HTTP/1.1 with lots of concurrent connections. 
To nail this down, try forcing your client to use HTTP/1.1 and see if the requests start getting distributed across many ARM FEs.
```

 - ForceAttemptHTTP2 as true

RoleInstance | userAgent | count_
-- | -- | --
FrontdoorWeb-vmss-fdweb_213 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 13,930
FrontdoorWeb-vmss-fdweb_107 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 12,190
FrontdoorWeb-vmss-fdweb_381 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 6,534
FrontdoorWeb-vmss-fdweb_285 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 599
FrontdoorWeb-vmss-fdweb_234 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 145
FrontdoorWeb-vmss-fdweb_300 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 100
FrontdoorWeb-vmss-fdweb_253 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 100
FrontdoorWeb-vmss-fdweb_186 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 100
FrontdoorWeb-vmss-fdweb_10 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 68
FrontdoorWeb-vmss-fdweb_122 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 7

 - ForceAttemptHTTP2 as false

RoleInstance | userAgent | count_
-- | -- | --
FrontdoorWeb-vmss-fdweb_134 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 1,139
FrontdoorWeb-vmss-fdweb_376 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 1,100
FrontdoorWeb-vmss-fdweb_66 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 979
FrontdoorWeb-vmss-fdweb_186 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 918
FrontdoorWeb-vmss-fdweb_278 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 886
FrontdoorWeb-vmss-fdweb_370 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 881
FrontdoorWeb-vmss-fdweb_85 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 829
FrontdoorWeb-vmss-fdweb_200 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 739
FrontdoorWeb-vmss-fdweb_227 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 680
FrontdoorWeb-vmss-fdweb_192 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 657
FrontdoorWeb-vmss-fdweb_153 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 647
FrontdoorWeb-vmss-fdweb_206 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 646
FrontdoorWeb-vmss-fdweb_36 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 615
FrontdoorWeb-vmss-fdweb_55 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 601
FrontdoorWeb-vmss-fdweb_234 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 585
FrontdoorWeb-vmss-fdweb_338 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 551
FrontdoorWeb-vmss-fdweb_142 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 435
FrontdoorWeb-vmss-fdweb_346 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 414
FrontdoorWeb-vmss-fdweb_221 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 381
FrontdoorWeb-vmss-fdweb_159 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 320
FrontdoorWeb-vmss-fdweb_276 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 309
FrontdoorWeb-vmss-fdweb_237 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 305
FrontdoorWeb-vmss-fdweb_318 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 296
FrontdoorWeb-vmss-fdweb_213 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 288
FrontdoorWeb-vmss-fdweb_295 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 287
FrontdoorWeb-vmss-fdweb_255 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 269
FrontdoorWeb-vmss-fdweb_46 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 268
FrontdoorWeb-vmss-fdweb_31 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 253
FrontdoorWeb-vmss-fdweb_341 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 252
FrontdoorWeb-vmss-fdweb_368 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 246
FrontdoorWeb-vmss-fdweb_290 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 237
FrontdoorWeb-vmss-fdweb_10 | Go/go1.19.4 (amd64-linux) go-autorest/v14.2.1   disk.csi.azure.com/v1.26.0 OSS-kubectl | 236

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
fix: set ForceAttemptHTTP2 to increase ARM throttling limit
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
fix: set ForceAttemptHTTP2 to increase ARM throttling limit
```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by nilo19** [comment]
Do we need to test the performance of the cloud provider as well?

**Comment by andyzhangx** [comment]
> While HTTP/2 has many advantages abstractly, we have not been able to put in in mainline use in the control plane so far primarily because it doesn’t mesh well with the load-balanced architecture. You’d have to invest quite a bit in connection health and load-balancing management on the client side to get the robustness of HTTP/1.1 with lots of concurrent connections. 
> To nail this down, try forcing your client to use HTTP/1.1 and see if the requests start getting distributed across many ARM FEs.

@nilo19 actually the auto trust(proxy) used by aks ccm and csi driver are already set this value as false, this change would make value in open source as identical as managed ccm and csi driver.

**Comment by serbrech** [comment]
What about the impact on SNAT exhaustion @andyzhangx ? has this been conisdered/tested?

**Comment by andyzhangx** [comment]
> What about the impact on SNAT exhaustion @andyzhangx ? has this been conisdered/tested?

@serbrech there is `MaxIdleConnsPerHost:   100` setting which means it would occupy at most 100 ports at most, and in the csi driver load test, it's 10 Azure RoleInstances for `true` value, and 97 Azure RoleInstances for `false` value, so it's increasing 97-10=87 ports during load test.

**Pull request merged**
