### PR TITLE
cherry-pick #926 #936 #978 to release-0.7

### PR DESCRIPTION
**Pull request by luncj**
#### What this PR does / why we need it:
refer #926 #936 #978
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/ok-to-test

**Comment by luncj** [comment]
poke

**Review by feiskyer — APPROVED** [review]

**Pull request merged**
