### PR TITLE
Partly decouple k/k

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Partly decouple k/k.
Ref: #352

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
could you provide more details about this PR? and how did you update those dependencies?

**Comment by nilo19** [comment]
> could you provide more details about this PR? and how did you update those dependencies?

This PR partly decouple cloud-provider-azure from k/k by copying the deps in k/k into this repo. The vendor is updated by `go mod tidy` and `go mod vendor`.

**Comment by nilo19** [comment]
further work:
decouple k/k/cmd/controller-manager after https://github.com/kubernetes/kubernetes/pull/91014#issuecomment-659568133 get merged,
decouple k/k/test/e2e/framework, ref: https://docs.google.com/document/d/1QgYEmdrdIirRCGBi2j55yb88WCZOGBqOJw7xj3s05PI/edit#

**Comment by nilo19** [comment]
considering https://github.com/kubernetes/kubernetes/pull/92201 and https://github.com/kubernetes/kubernetes/pull/91474/files, these two parts shall be decoupled in probably early 1.20.

**Pull request merged**
