### PR TITLE
chore: adopt go mod pattern and regenerate clients

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
adopt go module
regenerate mock clients using mockgen
shrink the code base to help reviewer review the commit.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

related: #931 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
@nilo19 @feiskyer Is there any other advice ? Thanks!

**Comment by feiskyer** [comment]
Could we continue keeping the vendor? (which is same as kubernetes/kubernetes repo)

**Comment by MartinForReal** [comment]
ok

**Pull request closed without merging**
