### PR TITLE
e2e: add e2e test for annotation `service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges`

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
add e2e test for annotation `service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges`
```

### CODE REVIEW

**Comment by nilo19** [comment]
/hold
would pass the test when the nrp issue is resolved

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
