### PR TITLE
Track2 sdk:bump armcompute to v6

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Track2 sdk:bump armcompute to v6
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feiskyer** [comment]
@MartinForReal seesm e2e tests are not triggered?

**Comment by MartinForReal** [comment]
yes e2e tests will be triggered only when new clients are imported

**Pull request merged**
