### PR TITLE
Rename E2E environment variables for consistency across projects

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Following up on kubernetes-sigs/azurefile-csi-driver#459.

cloud-provider-azure e2e uses different environment variable names than everything else (https://github.com/kubernetes-sigs/cloud-provider-azure/blob/83ec139e2224561e12e896c483b31cb08ad351a2/site/content/en/development/e2e/e2e-tests-azure.md). Updating kubetest to set the same environment variables for consistency. The new names are also slightly better syntactically IMO.

/hold until https://github.com/kubernetes/test-infra/pull/21917 is merged

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
Rename E2E environment variables for consistency across projects
```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
(for testing)

/test pull-cloud-provider-azure-e2e-ccm-capz

**Comment by nilo19** [comment]
The kubeconfig is missing

**Comment by feiskyer** [comment]
while most test failures reported "No credentials provided for AAD application" (test failure is expected), the logs of capz job is very confusing as there's no error reported there. @CecileRobertMichon  could you help to fix error logs of capz job?

**Comment by CecileRobertMichon** [comment]
@feiskyer I'm still working on the capz job, you can ignore it for now.

The other ones should be fixed once the jobs get the latest kubetest image.

**Comment by CecileRobertMichon** [comment]
/hold cancel

@feiskyer this is ready. I'm working on fixing the capz test in #607.

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request merged**
