### PR TITLE
Remove Calico ClusterResourceSets from CAPZ templates

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it: 

Following https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2495, CAPZ ci-entrypoint.sh script will install Calico via Helm so the templates no longer need to include Calico as a ClusterResourceSet for Linux (windows still needs it for now). This should not merge until CAPZ release-1.7 is used in the tests.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

This should not merge until CAPZ release-1.7 is used in the tests

**Comment by CecileRobertMichon** [comment]
@lzhecheng FYI I tested the Linux templates in this repo with the new ci-entrypoint.sh script after https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2495 merged and it seems to be working so the new release should not break cloud-provider tests. However, the ci-version ones that have both Linux and Windows might need this patch in order to work correctly. I've opened this now so we can start reviewing/testing, but it should not merge until CAPZ v1.7 is released in January and the jobs start using that branch to run tests.

Will follow up early January after I'm back from Holidays.

**Comment by jackfrancis** [comment]
🥳

**Pull request merged**
