### PR TITLE
cherry-pick #926 #936 #978 to release-1.1

### PR DESCRIPTION
**Pull request by luncj**
#### What this PR does / why we need it:
refer #926 #936 #978
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/ok-to-test

**Comment by luncj** [comment]
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/979/commits/bde93330612356c24ab4be5bb0c8647541927188 update doc site deps (refer to #975 )

**Comment by luncj** [comment]
poke

**Pull request merged**
