### PR TITLE
Enable Windows for credential provider pipeline

### PR DESCRIPTION
**Pull request by lzhecheng**
#### What type of PR is this?
/kind testing

#### What this PR does / why we need it:
* Enable Windows credential provider e2e
* credential provider code: %w -> %v. Otherwise, e.g. "Failed to initialize ACR provider: %!w(*fmt.wrapError=&{failed to create service principal token: no credentials provided for Azure cloud provider 0xc0000a5620})"
* credential provider cluster template: 1. log level to 4, 2. acr-credential-provider.exe, 3. credential-provider-config-win.yaml - c:\k\azure.json
#### Which issue(s) this PR fixes:

Fixes #
Related #2403

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
does it work now? and how can we get credential provider logs?

**Comment by lzhecheng** [comment]
> does it work on Windows now? and how can we get credential provider logs?

Yes, there were some incorrect configs, which are fixed in this PR.
Those logs are in kubelet one.

**Pull request merged**
