### PR TITLE
build: fix generating release note

### PR DESCRIPTION
**Pull request by luncj**
#### What this PR does / why we need it:
fix generating release note. before this PR, the `branch to scrape` is always equal to `master`.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
@luncj thanks for the fix. Please update the releases with incorrect release notes if possible.

**Comment by luncj** [comment]
@nilo19 😂 can you please help me to trigger the following commands (as I am not the kubernetes-sigs member)
/cherry-pick release-1.23
/cherry-pick release-1.1
/cherry-pick release-1.0
/cherry-pick release-0.7

**Comment by nilo19** [comment]
@luncj there is no hyphen in between
/cherrypick release-1.23
/cherrypick release-1.1
/cherrypick release-1.0
/cherrypick release-0.7

**Comment by nilo19** [comment]
@luncj it looks manual cherry-pick is needed

**Comment by luncj** [comment]
😂  thanks anyway, I will do it manually.

**Pull request merged**
