### PR TITLE
Add lints for loop pointer

### PR DESCRIPTION
**Pull request by lzhecheng**
#### What type of PR is this?
/kind testing

#### What this PR does / why we need it:
Add lints for loop pointer. exportloopref and looppointer
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lzhecheng** [comment]
Added both lints mentioned here: https://github.com/golangci/golangci-lint/issues/1404

**Comment by MartinForReal** [comment]
https://github.com/brutella/dnssd/issues/26
https://golangci-lint.run/usage/linters/#revive https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range-val-in-closure
I'm wondering if above tools will meet your need.

**Comment by lzhecheng** [comment]
> [brutella/dnssd#26](https://github.com/brutella/dnssd/issues/26) https://golangci-lint.run/usage/linters/#revive https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#range-val-in-closure I'm wondering if above tools will meet your need.

revive is already in current code lint but it doesn't seem enough?

**Pull request merged**
