### PR TITLE
add test comment

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

This PR tests that the capz presubmit job runs, and passes.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@feiskyer FYI, I opened this test PR to validate that capz tests run for cherry-pick PRs (I used release-1.1 for this test)

I notice that the e2e-ccm-capz tests are failing, does that suggest that we actually have some work to do to make capz functional on k8s 1.22? Because we haven't been running these tests before, maybe we're finding out now that there is work to do here.

Thanks!

**Comment by feiskyer** [comment]
We never run these tests before, so would need to check the logs and confirm why they are failing.

**Comment by feiskyer** [comment]
Most errors were caused by networking issues, retrying should work:

```
got error Get "http://52.136.123.190:80": dial tcp 52.136.123.190:80: i/o timeout, will retry
got error Get "http://23.100.29.61:80": dial tcp 23.100.29.61:80: i/o timeout, will retry
got error Get "http://20.117.138.99:80": dial tcp 20.117.138.99:80: i/o timeout, will retry
 ```

And one of them was caused by the following eror:

```
"Private static IP address 10.0.0.5 does not belong to the range of subnet prefix 10.1.0.0/16."
```

@jackfrancis any patterns in different capz versions to select the cluster's subnet?

**Pull request closed without merging**
