### PR TITLE
Delete unused scripts.

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Delete unused scripts.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feiskyer** [comment]
let's keep this for manual run in case there are something wrong in the github actions?

**Comment by MartinForReal** [comment]
the script has been merged into documentation branch.

**Pull request closed without merging**
