### PR TITLE
Feature: Add ServiceAnnotationLoadBalancerIP for deprecated LoadBalancerIP

### PR DESCRIPTION
**Pull request by AfrouzMashayekhi**
#### What type of PR is this?
/kind feature
/kind api-change
/kind deprecation

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1781

#### Does this PR introduce a user-facing change?

```release-note
As Kubernetes v1.24, service.Spec.LoadbalancerIP may be removed in future Kubernetes API version, so we need to add a new annotation service.beta.kubernetes.io/azure-load-balancer-ip for setting Azure LoadBalancerIP
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jwtty** [comment]
Looks like the change is not compatible for existing services still using `service.spec.LoadBalancerIP`.

**Comment by AfrouzMashayekhi** [comment]
@jwtty So should I set both `service.spec.loadBalancerIP` and the annotation?

**Comment by nilo19** [comment]
@AfrouzMashayekhi thanks for the contribution!
1. Please add an E2E test.
2. If the check of spec.LoadBalancerIP is fully deleted, a lot of existing clusters will be broken. We need to make both options work at this stage, and mark the spec.LoadBalancerIP as deprecated. We will remove it in the future, but not now.

**Comment by nilo19** [comment]
I would suggest the annotation overweights the service spec, if both are set at a time.

**Comment by jwtty** [comment]
I feel a wrapper to get service LoadBalancerIP might be a solution: `getServiceLoadBalancerIP()`:
```
if annotation is set:
  return annotation value
return service.spec.LoadBalancerIP
```
Similar function to refer would be [getClusterFromPIPClusterTags](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/provider/azure_loadbalancer.go#L1141)

What do you think? @nilo19 @AfrouzMashayekhi

**Comment by lzhecheng** [comment]
@AfrouzMashayekhi do you still have time on this PR? I am going to implement dualstack service support which needs this lb annotation change. Thanks.

**Comment by lzhecheng** [comment]
@AfrouzMashayekhi Also to support dualstack, I hope the `ServiceAnnotationLoadBalancerIP` can be `ServiceAnnotationLoadBalancerIPs`.

**Comment by AfrouzMashayekhi** [comment]
Hi @lzhecheng! Sorry for the late response; unfortunately, I'm occupied. Feel free to assign it to yourself

**Comment by lzhecheng** [comment]
> Hi @lzhecheng! Sorry for the late response; unfortunately, I'm occupied. Feel free to assign it to yourself

Got it. I will do it for dual-stack as well.

**Comment by yang-wang11** [comment]
@AfrouzMashayekhi @lzhecheng 
Hey, May I know whether there have any volunteers who still supporting this feature?  we have an emergency case for supporting the `Static IP` for load balancers. so I hope we can use the LB annotation(` "service.beta.kubernetes.io/azure-load-balancer-ip"`) instead of the deprecated field `LoadBalancerIP` for our clusters.
If no one else is available, I'd be happy to help with this

**Comment by lzhecheng** [comment]
> 

Hello, I will do it.
Now I am working on supporting dual-stack and it takes some time. However, I can make a small commit first with single stack annotation.

**Comment by yang-wang11** [comment]
@lzhecheng 
thanks for the quick response.  I suppose your change will be compatible with the legacy field, right?

**Comment by lzhecheng** [comment]
> @lzhecheng thanks for the quick response. I suppose your change will be compatible with the legacy field, right?

Yes, sure.

**Comment by lzhecheng** [comment]
This feature has been supported in #2428 . Closing this one.

**Pull request closed without merging**
