### PR TITLE
docs: remove auto approval restriction

### PR DESCRIPTION
**Pull request by aslafy-z**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Update the documentation to take https://github.com/kubernetes-sigs/cloud-provider-azure/pull/1863 in account.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1859

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jwtty** [comment]
Thanks for making the contribution!

**Comment by jwtty** [comment]
Fixing the codespell failures in PR #4870

**Comment by jwtty** [comment]
@aslafy-z The above spellcheck PR is merged. Could you please rebase your branch so that the test can pass? Thanks again.

**Comment by aslafy-z** [comment]
@jwtty I rebased the MR, can you approve the CI run? Thank you

**Pull request merged**
