### PR TITLE
chore: Update azure sdk for go to use a newer network package

### PR DESCRIPTION
**Pull request by nearora-msft**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by feiskyer** [comment]
@nearora-msft has the API version "2021-02-01" available in all clouds?

**Comment by andyzhangx** [comment]
pls use `./hack/update-dependencies.sh` to update go vendor files.

**Comment by andyzhangx** [comment]
> @nearora-msft has the API version "2021-02-01" available in all clouds?

confirmed from azure file team, `2021-02-01` is available in all clouds

**Comment by nearora-msft** [comment]
> pls use `./hack/update-dependencies.sh` to update go vendor files.

Done

**Pull request merged**
