### PR TITLE
feat: Support controller health check in ccm

### LINKED ISSUE #1071: Add health check for controllers
#### What would you like to be added:

We need to add health check for all controllers to gain insight if some of them are in failed state.
Example: https://github.com/kubernetes/cloud-provider/blob/ffb14a0934a04d96f6f92a9c801140193ec87bbf/app/controllermanager.go#L289-L303

#### Why is this needed:

There is a chance that the service controller is not working porperly ([test](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1070/pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb/1486488608226414592), [cloud controller manager log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1070/pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb/1486488608226414592/artifacts/k8s-master-21859912-0/cloud-controller-manager-k8s-master-21859912-0_kube-system_cloud-controller-manager-ce4270a5f72e9fc160320eeccc2e3abf56e7706e5f60eb2a100db763a093c744.log)), and we do not know the reason. If we have health checks set on each controllers, we will get more context about the failures.

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

fixes #1071

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
feat: Support controller health check in ccm
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
Can we find the corresponding error log if the health check fails?

**Comment by MartinForReal** [comment]
> Can we find the corresponding error log if the health check fails?

kubelet will generate an event for pod, but error msg is not included.

**Comment by nilo19** [comment]
@lzhecheng perhaps we need to collect those pod events in test-infra to gain insight into the failing ccm pods.
/lgtm
/approve

**Comment by MartinForReal** [comment]
@lzhecheng Could you please update release note as required? Thanks!

**Comment by lzhecheng** [comment]
> @lzhecheng Could you please update release note as required? Thanks!

Sure

**Pull request merged**
