### PR TITLE
Update k8s.io/legacy-cloud-providers to v0.17.3

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update k8s.io/legacy-cloud-providers to v0.17.3.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by feiskyer** [comment]
@ialidzhikov Since you have already started the work, could you help upgrading k8s vendors to master branch instead? we want the master branch keep updates with k8s master branch for preparing v1.18.

**Comment by ialidzhikov** [comment]
> @ialidzhikov Since you have already started the work, could you help upgrading k8s vendors to master branch instead? we want the master branch keep updates with k8s master branch for preparing v1.18.

Yes, makes sense. I will adapt the PR to v1.18.

/hold

**Comment by ialidzhikov** [comment]
Sorry guys, currently busy with other stuffs. Closing this PR for now. 😕 

/close

**Pull request closed without merging**
