### PR TITLE
remove docker login

### PR DESCRIPTION
**Pull request by mainred**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
`docker login` is introduced in https://github.com/kubernetes-sigs/cloud-provider-azure/pull/974, but as https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1962 is merged which do `docker login` before we push image through `docker buildx` as an overall temporary fix, we should delete the unused code here.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Comment by mainred** [comment]
pull-cloud-provider-azure-e2e-ccm-capz uses cluster-api-provider-azure release-1.0 which has not include this workaround

``` 
 - base_ref: release-1.0
    org: kubernetes-sigs
    path_alias: sigs.k8s.io/cluster-api-provider-azure
    repo: cluster-api-provider-azure
    workdir: true
```

**Comment by feiskyer** [comment]
would it cause any issues if we keep this workaround for a while?

**Comment by mainred** [comment]
> would it cause any issues if we keep this workaround for a while?

Not at all, just want to remove redundant code. But currently the cluster-api-provider-azure used in pull-cloud-provider-azure-e2e-ccm-capz is `release-1.0` which has no `docker login` workaround. So let's pause this PR

**Comment by feiskyer** [comment]
@mainred it is in release-1.1 per https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1974. Should we switch our test from release-1.1 and remove our workaround?

**Comment by mainred** [comment]
@feiskyer please take a look
cc @andyzhangx  for csi drivers

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
