### PR TITLE
add projected sa token config

### PR DESCRIPTION
**Pull request by sonasingh46**
#### What this PR does / why we need it:
This PR adds helm config to project service account token for cloud controller manager which is required for workload identity. 

#### Which issue(s) this PR fixes:

Partially Fixes https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3589

#### Does this PR introduce a user-facing change?

```release-note
Add config to project service account token for workload identity
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by sonasingh46** [comment]
@MartinForReal -- How can I fix the `test-helm` errors? I updated the readme.

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Review by feiskyer — COMMENTED** [review]
Just noticed an existing chart is bumped in this PR. Could you bump the chart version and re-generate again?

/lgtm cancel

**Comment by sonasingh46** [comment]
@feiskyer -- Done

**Comment by andyzhangx** [comment]
@sonasingh46 we are hitting lots of following errors in the csi driver e2e test:

```
Release "cloud-provider-azure" does not exist. Installing it now.
Error: 1 error occurred:
	* Deployment.apps "cloud-controller-manager" is invalid: spec.template.spec.containers[0].volumeMounts[3].name: Not found: "projectedToken"
CCM cluster CIDR: 192.168.0.0/16
Installing cloud-provider-azure components via helm
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/kubeconfig
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/kubeconfig
Error: UPGRADE FAILED: failed to create resource: Deployment.apps "cloud-controller-manager" is invalid: spec.template.spec.containers[0].volumeMounts[3].name: Not found: "projectedToken"
```
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/2035/pull-azuredisk-csi-driver-e2e-capz/1720087417538482176

How can I overcome this issue?

**Comment by andyzhangx** [comment]
ok, I see it's fixed by https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4921

**Pull request merged**
