### PR TITLE
test only

### PR DESCRIPTION
**Pull request by nilo19**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
@nojnhuh it seems the workload identity does not work. Do you know what is still missed?
pull-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz uses this cloud provider config json:
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json

**Comment by nojnhuh** [comment]
> @nojnhuh it seems the workload identity does not work. Do you know what is still missed? pull-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz uses this cloud provider config json: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/tests/k8s-azure/manifest/cluster-api/cloud-config-vmss-default.json

rg-cleanup seems to have gotten in the way of collecting logs this time, so I'm not sure. I'll run this again and add a tag to the resource group manually to keep rg-cleanup from deleting it after 4 hours.

/test pull-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz

**Comment by nojnhuh** [comment]
I'm actually a little surprised this passed without https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5050. Running this again to make sure that doesn't actually break the test.

/test pull-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz

**Comment by nojnhuh** [comment]
The `multi-slb` job uses a template that needs an update like #6724 but I'm hoping these other jobs should now also be passing:
/test pull-cloud-provider-azure-e2e-ccm-vmss-shared-probe-capz
/test pull-cloud-provider-azure-e2e-ccm-vmssflex-capz

**Pull request closed without merging**
