### PR TITLE
use batch operation for azure disk attach/detach

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
use batch operation for azure disk attach/detach
This PR use batch operation for disk attach/detach, that would improve disk attach/detach operation speed quite a lot, e.g. if we attach 20 disks to one vmss instance at one time, with this PR, only two disk attach operations would be triggered, that's 10x faster than original.

 - For attach disk operation, there is a queue called `attachDiskMap `
 - For detach disk operation, there is a queue called `detachDiskMap `

```
	// disk queue that is waiting for attach or detach on specific node
	// <nodeName, map<diskURI, *AttachDiskOptions/DetachDiskOptions>>
	attachDiskMap sync.Map
	detachDiskMap sync.Map
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
move  pkg/mockvmsets to provider folder since there is a cycle import error if not move:
```
# sigs.k8s.io/cloud-provider-azure/pkg/provider
package sigs.k8s.io/cloud-provider-azure/pkg/provider (test)
        imports sigs.k8s.io/cloud-provider-azure/pkg/mockvmsets
        imports sigs.k8s.io/cloud-provider-azure/pkg/provider: import cycle not allowed in test
FAIL    sigs.k8s.io/cloud-provider-azure/pkg/provider [setup failed]
```

**Release note**:
```
use batch operation for azure disk attach/detach
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
hold for review and testing on CSI driver first, testing result on in-tree driver is quite positive, will port this code change to CSI driver also.

**Comment by nilo19** [comment]
for the basic lb test failure: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/455

**Comment by nilo19** [comment]
need to investigate why the tests cluster cannot be built in pull-cloud-provider-azure-e2e-ccm

**Comment by nilo19** [comment]
pending https://github.com/kubernetes-sigs/cloud-provider-azure/pull/455

**Comment by nilo19** [comment]
do we have an e2e case for this one?

**Comment by andyzhangx** [comment]
> do we have an e2e case for this one?

yes, while it's not possible to run in this repo, I have ported code to 
- in-tree driver: https://github.com/kubernetes/kubernetes/pull/97265
- csi driver: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/635

**Pull request merged**
