### PR TITLE
chore: bump deps to fix CVEs for release-0.6

### PR DESCRIPTION
**Pull request by luncj**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
upgrade deps to fix CVEs

before:
ccm-0
after:
ccm-1

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
chore: upgrade `github.com/gogo/protobuf` to v1.3.2, `golang.org/x/crypto` to v0.0.0-20201216223049-8b5274cf687f and `golang.org/x/text` to v0.3.7
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
do we still need to support release-0.6?

**Comment by nilo19** [comment]
> do we still need to support release-0.6?

no

**Pull request merged**
