### PR TITLE
Update Helm chart for v1.30.1 and patch releases

### PR DESCRIPTION
**Pull request by mboersma**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Updates the cloud-provider-azure Helm chart to handle Kubernetes v1.30.x. Also updates to recent patch releases in active release branches.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by mboersma** [comment]
/hold

v1.30.0 is tagged but not released yet.

**Comment by mboersma** [comment]
@lzhecheng @jackfrancis could we merge this soon? We have a dependency on this chart in our publishing pipeline, so until there's 1.30 support here we can't publish 1.30 reference images for CAPZ.

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Pull request merged**
