### PR TITLE
[release-1.26] Fix leftover IPv6 support in e2e

### PR DESCRIPTION
**Pull request by lzhecheng**
#### What type of PR is this?
/kind testing

#### What this PR does / why we need it:
Fix leftover IPv6 support in e2e
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lzhecheng** [comment]
Fixes: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/5400

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request merged**
