### PR TITLE
Track2 sdk:migrate nsg client to track2 one

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Track2 sdk:migrate nsg client to track2 one
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
The apiVersion of network security group is bumped to 2024-01-01
The apiVersion of VirtualNetworkLink is bumpted to 2020-06-01
The apiVersion of PrivateZone is bumpted to 2020-06-01
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by zarvd — APPROVED** [review]
LGTM

**Review by feiskyer — APPROVED** [review]
lgtm

thanks for the migration

**Pull request merged**
