### PR TITLE
fix: add lock to avoid concurrent update on the cache

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
fix: add lock to avoid concurrent update on the cache

find more details here: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1556

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
fix: add lock to avoid concurrent update on the cache
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
fix: add lock to avoid concurrent update on the cache
```

### CODE REVIEW

**Comment by MartinForReal** [comment]
Cloud object will be removed from csi drivers if we adopt track2 sdk. I'm wondering if there is any other cache implementation in csi driver?

**Comment by MartinForReal** [comment]
related:https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4973/files

**Comment by nilo19** [comment]
Can you add unit tests to cover the race condition?

**Comment by andyzhangx** [comment]
> Can you add unit tests to cover the race condition?

@nilo19 ut added, let's fix it with sdk v1 first, and then port the change to sdk v2

**Comment by andyzhangx** [comment]
`pull-cloud-provider-azure-e2e-ccm-capz` failed due to capz cluster creation failed, not related to this PR

**Comment by nilo19** [comment]
lgtm, please don't forget to squash the commits.

**Comment by andyzhangx** [comment]
> lgtm, please don't forget to squash the commits.

@nilo19 done, there are two commits now: one bug fix and one ut commit.

**Comment by CecileRobertMichon** [comment]
/retest

job should be fixed now

**Pull request merged**
