### PR TITLE
test: enable federated identity test profile

### LINKED ISSUE #6621: k8s community infra migration: azureAuthConfigFromTestProfile needs federated identity
cloud-provider-azure jobs relying upon CAPZ are failing due to a new requirement for federated identity as part of the migration to k8s community infra on GKE and EKS.

Here is a sample test that shows this failure:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/cloud-provider-azure-master-capz-main/1813967116143955968

The cloud-provider-azure E2E test environment must rely upon an Azure client context running federated identity.

Ref: https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity#defaultazurecredential

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

This PR enabled federated identity test profiles, which are now required for E2E flows when using CAPZ clusters built at main. 

This is due to a requirement from the k8s community infra migration effort.

#### Which issue(s) this PR fixes:

Fixes #6621

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nojnhuh** [comment]
@nilo19 I have enough context here to resolve the merge conflicts since Jack is out this week. I can open PRs and tag you for reviews if that would be helpful.

**Comment by nilo19** [comment]
@nojnhuh let me change the test-infra job template and test if this works first.

**Comment by nilo19** [comment]
It seems not work.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/6638/pull-cloud-provider-azure-e2e-ccm-vmss-capz-eks-test/1815276613428842496
Job:
https://github.com/kubernetes/test-infra/pull/33048/files

**Comment by nojnhuh** [comment]
Added a comment on the test-infra PR. CAPZ on community clusters requires the release-1.16 or main branch, so updating that should ideally get the job passing.

**Pull request merged**
