### PR TITLE
Set LegacyServiceAccountTokenNoAutoGeneration to false for master/1.24 aks-engine configs

### PR DESCRIPTION
**Pull request by marosset**
…

Signed-off-by: Mark Rossetti <marosset@microsoft.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Sets `LegacyServiceAccountTokenNoAutoGeneration=false` for controller-manager feature gates as a mitigation to preserve previous SA token generation behaviors for aks-engine.

https://github.com/kubernetes/enhancements/pull/2800/files introduced this feature gate and set true-by-default.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by marosset** [comment]
We made the same updates to aks-engine templates used in Windows tests

https://github.com/kubernetes-sigs/windows-testing/pull/312 and https://github.com/kubernetes-sigs/windows-testing/pull/313

**Review by aramase — COMMENTED** [review]
/lgtm

**Comment by marosset** [comment]
Let me update the PR jobs too

**Comment by marosset** [comment]
> Let me update the PR jobs too

Hmm it looks like the PR jobs are using https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux.json which is shared between different versions of K8s.
Because of this I cannot add the new feature gate here.

I think we either need to update aks-engine to add this featuregate for v1.24-alpha.3+ or break up the configs.
I'm leaning towards updating aks-engine.

--Mark

**Pull request merged**
