### PR TITLE
[WIP] Test.

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
None.
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
sth wrong with the e2e test?

**Comment by nilo19** [comment]
> sth wrong with the e2e test?

yeah, for unknown reason.

**Comment by feiskyer** [comment]
no artifacts found for the failing tests, but seems #277 is passing the tests, let's wait a while for #277.

**Pull request closed without merging**
