### PR TITLE
uptake compute api version 2020-12-01

### PR DESCRIPTION
**Pull request by MirzaSikander**
/kind feature

**What this PR does / why we need it**:
Need to update to the latest Compute API version since it contains changes for Edge zone APIs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
Need to update to the latest Compute API version since it contains changes for Edge zone APIs.
```

### CODE REVIEW

**Comment by MirzaSikander** [comment]
gentle ping!

**Comment by andyzhangx** [comment]
@MirzaSikander  change lgtm, could you squash all commits? thanks.

**Comment by MirzaSikander** [comment]
Squashed!

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
thanks

**Comment by feiskyer** [comment]
The real API version hasn't been updated, e.g. 

```
// APIVersion is the API version for compute.
APIVersion = "2019-07-01"
```

Please make another change to update the API version that is really consumed.

**Comment by andyzhangx** [comment]
> The real API version hasn't been updated, e.g.
> 
> ```
> // APIVersion is the API version for compute.
> APIVersion = "2019-07-01"
> ```
> 
> Please make another change to update the API version that is really consumed.

this change should be very careful since it may break some regions, make sure `2020-12-01` has already been rolled out to all regions.

**Pull request merged**
