### PR TITLE
[Helm] Update nodeSelector and tolerations

### PR DESCRIPTION
**Pull request by atsai1220**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This allows the `cloud-controller-manager` to start on nodes with `etcd` taints by default. Additionally, allows configuration for additional taints if the user chooses. Currently this customization is not available at all.

Additionally allows configuration for `nodeSelector`. This is similar to how the `cloud-provider-aws` configures their Helm chart. https://github.com/kubernetes/cloud-provider-aws/blob/5db84490841ebd1eede368d03eb03c27dc556233/charts/aws-cloud-controller-manager/values.yaml#L16

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Thank you!

#### Does this PR introduce a user-facing change?

```release-note
- Add tolerations in values for cloud-controller-manager in Helm chart
- Add nodeSelector in values for cloud-controller-manager in Helm chart
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Comment by andyzhangx** [comment]
> I'm not sure if I understand the failing test. The PR is adding the change for the values and templates of the Helm chart and the test seems like it's failing because there is a difference. @andyzhangx

@lzhecheng could you help? thanks.

**Comment by feiskyer** [comment]
LGTM, but the chart validation failed. I think the validation failure means the yaml after rendering is not same as latest version under `repo/`.

@lzhecheng could you confirm?

**Comment by lzhecheng** [comment]
Will check

**Comment by lzhecheng** [comment]
I think you missed one part: Update version in `helm/cloud-provider-azure/Chart.yaml`. Make it something like `1.26.4+20230210` and then `make update-helm`.

**Comment by lzhecheng** [comment]
Also, could you please update doc as well?

**Comment by lzhecheng** [comment]
@atsai1220 could you please update the PR? Thanks.

**Comment by atsai1220** [comment]
I'm not sure how to proceed. Could you provide some hand holding? Thank you.

**Comment by lzhecheng** [comment]
> I'm not sure how to proceed. Could you provide some hand holding? Thank you.

My suggestion is to:
1. Rebase your PR
2. Update the version here to something like `1.26.4+20230215`: https://github.com/kubernetes-sigs/cloud-provider-azure/blob/79fbf0cddb68473a93ba2de140ffab070607abc1/helm/cloud-provider-azure/Chart.yaml#L16
3. Run `make update-helm`
4. Update the [README](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/79fbf0cddb68473a93ba2de140ffab070607abc1/helm/cloud-provider-azure/README.md) doc about your changes

**Comment by lzhecheng** [comment]
/close
@atsai1220 I have merged your commit with another PR. Thank you for the effort!

**Pull request closed without merging**
