### PR TITLE
Duplicate the in-tree cloud provider code to the out-of-tree repo

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
/kind cleanup

**What this PR does / why we need it**:
Since only bug fixes could be merged into the in-tree cloud provider from v1.20.0, we need to duplicate the in-tree code to the out-of-tree repo.

**Which issue(s) this PR fixes**:

Fixes #
Ref: https://github.com/kubernetes-sigs/cloud-provider-azure/issues/352

**Special notes for your reviewer**:

**Release note**:
```
Duplicate the in-tree cloud provider code to the out-of-tree repo
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
LGTM, let's check whether CI would be fixed by https://github.com/kubernetes/test-infra/pull/20230

**Comment by andyzhangx** [comment]
@nilo19 I see the config is still testing against in-tree driver:
https://github.com/kubernetes/test-infra/blob/132d8e19d709ef5f89c2995835156d43718ab94d/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L258-L260

try remove the above 2 lines and try again.

**Comment by nilo19** [comment]
> @nilo19 I see the config is still testing against in-tree driver:
> https://github.com/kubernetes/test-infra/blob/132d8e19d709ef5f89c2995835156d43718ab94d/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L258-L260
> 
> try remove the above 2 lines and try again.

thanks for reminding

**Comment by andyzhangx** [comment]
thanks, csi driver test works now.
Since the code is merged now, could you @nilo19 work on this issue: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/616? Once we have new vendoring on CSI driver, CSI driver development would be quite easier, thanks.

**Comment by nilo19** [comment]
> thanks, csi driver test works now.
> Since the code is merged now, could you @nilo19 work on this issue: [kubernetes-sigs/azuredisk-csi-driver#616](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/616)? Once we have new vendoring on CSI driver, CSI driver development would be quite easier, thanks.

sure thing.

**Pull request merged**
