### PR TITLE
Update to 2020-07-01/network

### PR DESCRIPTION
**Pull request by MirzaSikander**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Updates all the references for azure network API to point to `2020-07-01` .  This is needed to consume new features like `Edge Zones`. This pull request only contains the update to new version so that it can be tested in isolation. 
We decided not to update to `2020-08-01` because there are some concerns about breaking changes:
https://github.com/kubernetes-sigs/cloud-provider-azure/issues/403

**Special notes for your reviewer**:
Apart from the reference updates, there is only one logic change, which is in `pkg/provider/azure_standard.go`. Apparently, the property type for the field `InterfacePropertiesFormat.ProvisioningState` updated in between API versions, and is no longer a pointer type. Opened a bug on the azure sdk team: https://github.com/Azure/azure-sdk-for-go/issues/14261

Also a test `TestGetVirtualMachineScaleSetNetworkInterface` in `pkg/azureclients/interfaceclient/azure_interfaceclient_test.go` had to be updated because it was setting a readonly field which doesn't get marshalled anymore. More info here:
https://github.com/Azure/azure-sdk-for-go/issues/14263

**Release note**:
```
Updates all the references for azure network API to point to `2020-07-01` which is the latest API Version
```

### CODE REVIEW

**Comment by feiskyer** [comment]
Refer #403, the new network API 2020-08-01 has introduced a breaking change about the availability zone. We need to ensure zone-redundant resources are created on AZ regions.

Do you any API to query AZ regions?

/hold

**Comment by nilo19** [comment]
According to our discussion, mirza would use 2020-07-01, which is sufficient for him.

**Comment by MirzaSikander** [comment]
I have updated the title and the pull request description to indicate that we are only switching to 2020-07-01.

**Comment by MirzaSikander** [comment]
As mentioned in the pull request description, a test TestGetVirtualMachineScaleSetNetworkInterface in pkg/azureclients/interfaceclient/azure_interfaceclient_test.go had to be updated because it was setting a readonly field which doesn't get marshalled anymore. More info here:
https://github.com/Azure/azure-sdk-for-go/issues/14263

**Comment by feiskyer** [comment]
Could you also update the APIVersion for all the updated clients? one example is here (please do not touch AzureStackCloudAPIVersion):

https://github.com/kubernetes-sigs/cloud-provider-azure/blob/21a604f8f3cbc423a9e5c41c9823d628a321ab46/pkg/azureclients/loadbalancerclient/interface.go#L30-L31

**Comment by feiskyer** [comment]
> As mentioned in the pull request description, a test TestGetVirtualMachineScaleSetNetworkInterface in pkg/azureclients/interfaceclient/azure_interfaceclient_test.go had to be updated because it was setting a readonly field which doesn't get marshalled anymore. More info here:

Could you fix this test failure?

**Comment by MirzaSikander** [comment]
@feiskyer The clients have been updated and the test is fixed.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

/hold cancel

**Pull request merged**
