### PR TITLE
Refactor: reorg provider code: move interface reference to implementation

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
move interface reference to implementation
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
move interface reference to header of implementation.
no behavior change.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
<html>
<body>

/test pull-cloud-provider-azure-e2e-ccm-vmss-ip-lb-capz
--


<br class="Apple-interchange-newline">
</body>
</html>

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
