### PR TITLE
Track2 sdk: Add cache module in azclient

### PR DESCRIPTION
**Pull request by MartinForReal**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Track2 sdk: Add cache module in azclient
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mainred — COMMENTED** [review]
What's the difference between these cache from https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/cache/azure_cache.go?
And how are you going to use azclient/cache to replace pkg/cache/azure_cache?

**Comment by MartinForReal** [comment]
It is the same except that is is a module and it adopts golang generics. 
It will be a dependency of generated repo implementation.

**Comment by andyzhangx** [comment]
> [pkg/cache/azure_cache.go](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/cache/azure_cache.go)?

@MartinForReal so will you remove the [pkg/cache/azure_cache.go](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/cache/azure_cache.go)?

**Comment by MartinForReal** [comment]
yes. but we can keep it until it is not used.

**Review by mainred — APPROVED** [review]
Thanks for creating this PR. Since azclient is created as a separate module for more than just cloud-provider-azure,  we can share the cache.
I will approve the PR but please confirm the following questions are not blockers to this PR.

My concerns:
1. why we reinvent deepcopy?
2. How are we going to protect the release of this module? we don't have e2e for this.
3. when do we plan to onboard this module to cloud-provider-azure? asking this because I am working on vmss-cache etag change, and there's conflicts.

**Comment by MartinForReal** [comment]
For deepcopy, I believe @lzhecheng may have more context info.
the package have not been updated for a long time and there are unit tests. we will run e2e test suite when bumping the dependency.
Retrieving azure resource should be done by repository object if cache is required. The consumer will invoke get/list/update and delete function and repo object will hide any implementation details.Please refer to repository in pkg/provider/subnet

**Comment by andyzhangx** [comment]
why not just move the code from [pkg/cache/azure_cache.go](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/pkg/cache/azure_cache.go) to the azclient since that's tested and verified in long time?

**Comment by MartinForReal** [comment]
Yes. I moved these two files and related utils to azclient package and refactored the code by introducing generics. It will be better because we can enforce the type in cache.

**Comment by MartinForReal** [comment]
reflect.deepcopy doesn't copy value in sync.map @mainred

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by MartinForReal** [comment]
It will be used in track2 clients. We can verify the code when we bump to track2 clients. Existing code will not be changed.
I didn't change the logic except that generics are introduced. I would recommend to use this cache module because it has less dependencies and it is safer to update and revert the changes in this versionized module.

**Pull request merged**
