### PR TITLE
chore: reduce node LIST APIs in cloud-node-manager

### PR DESCRIPTION
**Pull request by feiskyer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Refer the codes below, cloud-node-manager is querying the node every 5 minutes to reconcile its addresses, but this API call is not actually required as there's already informers:

 https://github.com/kubernetes-sigs/cloud-provider-azure/blob/0e8ef48b6c170202b697428f94b94a57b19ff791/pkg/nodemanager/nodemanager.go#L178-L181

Hence, this PR replaces the node LIST with informer LIST, which would reduce the API calls to apiserver.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
chore: reduce node LIST APIs in cloud-node-manager
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feiskyer** [comment]
/hold cancel

Ready for review now.

**Comment by jackfrancis** [comment]
Hi @feiskyer @nilo19 can we cut patch releases with this fix ASAP?

Thanks!

**Comment by feiskyer** [comment]
@jackfrancis we have another set of cherry-picks. Need to wait for them

**Comment by feiskyer** [comment]
@jackfrancis v1.23.2, v1.1.5 and v1.0.9 have been released with this change.

**Comment by jackfrancis** [comment]
Thank you @feiskyer!

cc @JohnRusk

**Pull request merged**
