### PR TITLE
chore: upgrade to 2020-06-30/compute

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
 /kind api-change

**What this PR does / why we need it**:
chore: upgrade to 2020-06-30/compute

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
```console
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./provider/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./mockvmsets/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/diskclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/vmssclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/vmssvmclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/snapshotclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/vmsizeclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/vmclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/diskclient/mockdiskclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/vmssclient/mockvmssclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/snapshotclient/mocksnapshotclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/vmsizeclient/mockvmsizeclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/vmclient/mockvmclient/*.*
sed -i 's/2019-12-01\/compute/2020-06-30\/compute/g' ./azureclients/vmssvmclient/mockvmssvmclient/*.*
```

**Release note**:
```
none
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@nilo19 how to fix this issue, golangci-lint is just a code check tool, why it's included in vendor/modules.txt? We could remove this tool by replacing with github action.
```
level=error msg="Running error: context loading failed: failed to load program with go/packages: err: exit status 1: stderr: go: inconsistent vendoring in /home/prow/go/src/sigs.k8s.io/cloud-provider-azure:\n\tgithub.com/golangci/golangci-lint@v1.25.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt\n\nrun 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory\n"
make: *** [Makefile:164: test-lint] Error 3
```

also what's the following ut failure:
```
        	Test:       	TestListWithNextPage
    azure_containerserviceclient_test.go:402: missing call(s) to *mockarmclient.MockInterface.PrepareGetRequest(is anything, is anything) /home/prow/go/src/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go:386
    azure_containerserviceclient_test.go:402: missing call(s) to *mockarmclient.MockInterface.Send(is anything, is anything) /home/prow/go/src/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go:387
    azure_containerserviceclient_test.go:402: missing call(s) to *mockarmclient.MockInterface.CloseResponse(is anything, is anything) /home/prow/go/src/sigs.k8s.io/cloud-provider-azure/pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go:397
    azure_containerserviceclient_test.go:402: aborting test due to missing call(s)
--- FAIL: TestListWithNextPage (0.00s)
```

**Comment by nilo19** [comment]
There are some indirect dependencies. @andyzhangx 
```
❯ go mod graph | grep golangci
sigs.k8s.io/cloud-provider-azure github.com/golangci/golangci-lint@v1.25.0
github.com/golangci/lint-1@v0.0.0-20191013205115-297bf364a8e0 golang.org/x/tools@v0.0.0-20190311212946-11955173bddd
github.com/golangci/errcheck@v0.0.0-20181223084120-ef45e06d44b6 github.com/kisielk/gotool@v1.0.0
github.com/golangci/errcheck@v0.0.0-20181223084120-ef45e06d44b6 golang.org/x/tools@v0.0.0-20180221164845-07fd8470d635
github.com/golangci/golangci-lint@v1.25.0 honnef.co/go/tools@v0.0.1-2019.2.3
github.com/golangci/golangci-lint@v1.25.0 mvdan.cc/unparam@v0.0.0-20190720180237-d51796306d8f
github.com/golangci/golangci-lint@v1.25.0 mvdan.cc/lint@v0.0.0-20170908181259-adc824a0674b
github.com/golangci/golangci-lint@v1.25.0 mvdan.cc/interfacer@v0.0.0-20180901003855-c20040233aed
github.com/golangci/golangci-lint@v1.25.0 gopkg.in/yaml.v2@v2.2.8
github.com/golangci/golangci-lint@v1.25.0 golang.org/x/tools@v0.0.0-20200422022333-3d57cf2e726e
github.com/golangci/golangci-lint@v1.25.0 github.com/valyala/quicktemplate@v1.2.0
github.com/golangci/golangci-lint@v1.25.0 github.com/uudashr/gocognit@v1.0.1
github.com/golangci/golangci-lint@v1.25.0 github.com/ultraware/whitespace@v0.0.4
github.com/golangci/golangci-lint@v1.25.0 github.com/ultraware/funlen@v0.0.2
github.com/golangci/golangci-lint@v1.25.0 github.com/tommy-muehle/go-mnd@v1.3.1-0.20200224220436-e6f9a994e8fa
github.com/golangci/golangci-lint@v1.25.0 github.com/timakin/bodyclose@v0.0.0-20190930140734-f7f2e9bca95e
github.com/golangci/golangci-lint@v1.25.0 github.com/tetafro/godot@v0.2.5
github.com/golangci/golangci-lint@v1.25.0 github.com/stretchr/testify@v1.5.1
github.com/golangci/golangci-lint@v1.25.0 github.com/spf13/viper@v1.6.1
github.com/golangci/golangci-lint@v1.25.0 github.com/spf13/pflag@v1.0.5
github.com/golangci/golangci-lint@v1.25.0 github.com/spf13/cobra@v0.0.5
github.com/golangci/golangci-lint@v1.25.0 github.com/sourcegraph/go-diff@v0.5.1
github.com/golangci/golangci-lint@v1.25.0 github.com/sirupsen/logrus@v1.4.2
github.com/golangci/golangci-lint@v1.25.0 github.com/shirou/gopsutil@v0.0.0-20190901111213-e4ec7b275ada
github.com/golangci/golangci-lint@v1.25.0 github.com/securego/gosec@v0.0.0-20200103095621-79fbf3af8d83
github.com/golangci/golangci-lint@v1.25.0 github.com/ryancurrah/gomodguard@v1.0.2
github.com/golangci/golangci-lint@v1.25.0 github.com/pkg/errors@v0.8.1
github.com/golangci/golangci-lint@v1.25.0 github.com/nakabonne/nestif@v0.3.0
github.com/golangci/golangci-lint@v1.25.0 github.com/mitchellh/go-ps@v0.0.0-20190716172923-621e5597135b
github.com/golangci/golangci-lint@v1.25.0 github.com/mitchellh/go-homedir@v1.1.0
github.com/golangci/golangci-lint@v1.25.0 github.com/mattn/go-colorable@v0.1.4
github.com/golangci/golangci-lint@v1.25.0 github.com/matoous/godox@v0.0.0-20190911065817-5d6d842e92eb
github.com/golangci/golangci-lint@v1.25.0 github.com/maratori/testpackage@v1.0.1
github.com/golangci/golangci-lint@v1.25.0 github.com/jirfag/go-printf-func-name@v0.0.0-20191110105641-45db9963cdd3
github.com/golangci/golangci-lint@v1.25.0 github.com/jingyugao/rowserrcheck@v0.0.0-20191204022205-72ab7603b68a
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/unconvert@v0.0.0-20180507085042-28b1c447d1f4
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/revgrep@v0.0.0-20180526074752-d9c87f5ffaf0
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/prealloc@v0.0.0-20180630174525-215b22d4de21
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/misspell@v0.0.0-20180809174111-950f5d19e770
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/maligned@v0.0.0-20180506175553-b1d89398deca
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/lint-1@v0.0.0-20191013205115-297bf364a8e0
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/ineffassign@v0.0.0-20190609212857-42439a7714cc
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/gofmt@v0.0.0-20190930125516-244bba706f1a
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/gocyclo@v0.0.0-20180528134321-2becd97e67ee
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/goconst@v0.0.0-20180610141641-041c5f2b40f3
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/go-misc@v0.0.0-20180628070357-927a3d87b613
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/errcheck@v0.0.0-20181223084120-ef45e06d44b6
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/dupl@v0.0.0-20180902072040-3e9179ac440a
github.com/golangci/golangci-lint@v1.25.0 github.com/golangci/check@v0.0.0-20180506172741-cfe4005ccda2
github.com/golangci/golangci-lint@v1.25.0 github.com/gofrs/flock@v0.0.0-20190320160742-5135e617513b
github.com/golangci/golangci-lint@v1.25.0 github.com/go-lintpack/lintpack@v0.5.2
github.com/golangci/golangci-lint@v1.25.0 github.com/go-critic/go-critic@v0.4.1
github.com/golangci/golangci-lint@v1.25.0 github.com/fatih/color@v1.7.0
github.com/golangci/golangci-lint@v1.25.0 github.com/bombsimon/wsl/v3@v3.0.0
github.com/golangci/golangci-lint@v1.25.0 github.com/OpenPeeDeeP/depguard@v1.0.1

```

**Comment by nilo19** [comment]
@andyzhangx I think it is because of this line https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/hack/verify-golint.sh#L19

**Comment by andyzhangx** [comment]
> @andyzhangx I think it is because of this line https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/hack/verify-golint.sh#L19

could switch to use https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/hack/verify-golint.sh

**Comment by feiskyer** [comment]
> could switch to use https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/hack/verify-golint.sh

yes, let's switch to download the tool directly

**Comment by andyzhangx** [comment]
```
~/go/src/github.com/kubernetes-sigs/cloud-provider-azure/pkg/azureclients/containerserviceclient# go test
--- FAIL: TestListWithNextPage (0.00s)
    azure_containerserviceclient_test.go:401:
                Error Trace:    azure_containerserviceclient_test.go:401
                Error:          Not equal:
                                expected: 6
                                actual  : 3
                Test:           TestListWithNextPage
    azure_containerserviceclient_test.go:402: missing call(s) to *mockarmclient.MockInterface.PrepareGetRequest(is anything, is anything) /root/go/src/github.com/kubernetes-sigs/cloud-provider-azure/pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go:386
    azure_containerserviceclient_test.go:402: missing call(s) to *mockarmclient.MockInterface.Send(is anything, is anything) /root/go/src/github.com/kubernetes-sigs/cloud-provider-azure/pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go:387
    azure_containerserviceclient_test.go:402: missing call(s) to *mockarmclient.MockInterface.CloseResponse(is anything, is anything) /root/go/src/github.com/kubernetes-sigs/cloud-provider-azure/pkg/azureclients/containerserviceclient/azure_containerserviceclient_test.go:397
    azure_containerserviceclient_test.go:402: aborting test due to missing call(s)

```

**Comment by nilo19** [comment]
for the golangci-lint problem:
https://github.com/kubernetes-sigs/cloud-provider-azure/pull/446

**Pull request merged**
