### PR TITLE
cherry-pick from #921 to release-0.7 (build: cross-compile under linux/amd64 platform)

### PR DESCRIPTION
**Pull request by luncj**
#### What this PR does / why we need it:
refer #921
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feiskyer** [comment]
+ ./scripts/ci-entrypoint.sh bash -c 'cd ${GOPATH}/src/sigs.k8s.io/cloud-provider-azure && make test-ccm-e2e'
Detected go version: go version go1.15.15 linux/amd64.

CI failed because of too old Go version.

**Comment by nilo19** [comment]
> 

I have informed the upstream team to check this issue.

**Pull request merged**
