### PR TITLE
[e2e] Improve pls and azure-pip-tags tests

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
* If failure to get a private link service, GetPrivateLinkService returns error with "not found"
* When checking azure-pip-tags, ignore "kubernetes-cluster-name" and "service"
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jwtty** [comment]
Not able to approve, but lgtm. Thanks!

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
