### PR TITLE
build: cross-compile under linux/amd64 platform

### PR DESCRIPTION
**Pull request by luncj**
#### What type of PR is this?
/kind perf

#### What this PR does / why we need it:

After #855, a new issue occurred: building `arm` and `arm64` images costs lots of time (sample: [build log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/894/pull-cloud-provider-azure-e2e-ccm/1465158916143845376/build-log.txt) and search `GOARCH=arm go build`). The previous Dockerfile had specified the build platform as the same as the target platform which makes it compile the `arm` and `arm64` images with the help of `QEMU`.

And this PR try to use `linux/amd64` as the unified build platform, and the benchmark is as follows:
| Build ARCH | Target ARCH | Cost Time | Remark |
| --- | --- | --- | --- |
| amd64 | amd64 | ~20s |  |
| arm64 | arm64 | ~700s | with QEMU |
| arm | arm | ~3000s | with QEMU |
| amd64 | arm64 | ~20s | without QEMU |
| amd64 | arm | ~20s | without QEMU |

ref:
- https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images
- https://github.com/moby/buildkit/issues/1513
- https://ahmedkrmn.github.io/TCG-Continuous-Benchmarking/Measuring-QEMU-Performance-in-System-Mode/

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test
would you sign the CLA?

**Comment by luncj** [comment]
I signed it

**Review by feiskyer — APPROVED** [review]
The building time improvements are awesome! 

/lgtm

**Pull request merged**
