### PR TITLE
fix: update osversion in Makefile manifest-node-manager-image-window

### PR DESCRIPTION
**Pull request by monianshouhou**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The old os-version in windows manifest-image can't be recognized. Os-version must be the official version like "10.0.17763.3165", not "1809". 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
<html>
<body>


/test pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by monianshouhou** [comment]
Give it a try for fixing CNM image pulling problem.

**Pull request merged**
