### PR TITLE
Upgrade Kubernetes vendor to v1.17.0

### PR DESCRIPTION
**Pull request by chewong**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

- Upgraded Kubernetes vendor to v1.17.0 (The git hash is `70132b0f130a` according to https://github.com/kubernetes/kubernetes/releases/tag/v1.17.0)
- Upgraded a bunch of 'replace' directives
- Upgraded go version in Dockerfiles from 1.12.9 to 1.13.4

/assign @feiskyer 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
Upgrade Kubernetes vendor to v1.17.0 
```

### CODE REVIEW

**Comment by chewong** [comment]
/hold
e2e tests are still testing on k8s release-1.16 branch.

**Comment by feiskyer** [comment]
New release of cloud-provider-azure is pending on this. @chewong let's merge the PR and update test-infra jobs in a following PR?

**Comment by chewong** [comment]
Sounds good.
/hold cancel

**Pull request merged**
