### PR TITLE
[release-1.27] fix: Keep auth envs when building e2e azure clients

### PR DESCRIPTION
**Pull request by nilo19**
#### What this PR does / why we need it:

/kind failing-test

fix: Keep auth envs when building e2e azure clients

#### Which issue(s) this PR fixes:

Fixes #
Partly https://github.com/kubernetes-sigs/cloud-provider-azure/issues/6577

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
@nojnhuh let's see if this would fix.

**Review by nojnhuh — COMMENTED** [review]
/lgtm

**Comment by nilo19** [comment]
We've already had https://github.com/kubernetes-sigs/cloud-provider-azure/commit/3b749bee00c7ed802a91007c5870107d9d232601
But the acr login still failed.

**Comment by nojnhuh** [comment]
> We've already had [3b749be](https://github.com/kubernetes-sigs/cloud-provider-azure/commit/3b749bee00c7ed802a91007c5870107d9d232601) But the acr login still failed.

This is failing in a different test where it does a `docker login`, not `az login` like was fixed in #6675. Here's where it was failing before: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/6638/pull-cloud-provider-azure-e2e-ccm-vmss-capz-eks-test/1816593076194381824

I see the `docker login` was removed in #4815 but seems not to have been cherry-picked to release-1.27 or release-1.28. Does #4824 also need to be cherry-picked here?

**Pull request merged**
