### PR TITLE
[release-1.25] Remove unnecessary probe port check

### PR DESCRIPTION
**Pull request by lzhecheng**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Remove unnecessary probe port check. GetHealthProbeConfigOfPortFromK8sSvcAnnotation() has checked. Add a e2e test.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
@lzhecheng Could you please rebase the branch ?

**Comment by lzhecheng** [comment]
> @lzhecheng Could you please rebase the branch ?

I think it has been rebased.

**Pull request merged**
