### PR TITLE
chore: support deploy capz clusters by make target

### PR DESCRIPTION
**Pull request by nilo19**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

chore: support deploy capz clusters by make target

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Support creating capz clusters by `make deploy-cluster`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsturtevant** [comment]
We have several ways to deploy clusters via make file currently:

- https://capz.sigs.k8s.io/developers/development.html#creating-a-dev-cluster
- https://capz.sigs.k8s.io/developers/development.html#e2e-testing
- https://capz.sigs.k8s.io/developers/development.html#conformance-testing
- https://capz.sigs.k8s.io/developers/development.html#tilt-for-dev-in-capz (less automatable)

I would be hesitant to add another way because it is already challenging to keep them all in sync (https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1372 and https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/1192 as examples).

Is there something missing from the other solutions that we could improve upon?

**Comment by CecileRobertMichon** [comment]
I believe the intention here is to store CAPZ templates for testing that are specific to the external cloud provider, similar to how cloud-provider-azure has AKS Engine json apimodels in https://github.com/kubernetes-sigs/cloud-provider-azure/tree/89389a43eaef2e1c15480389e111399d48266725/tests/k8s-azure/manifest. 

But I agree with @jsturtevant that duplicating code from CAPZ for creating management clusters and workload clusters via makefile seems it requires effort to keep them in sync long term. How about keeping the templates in the repo but using clusterctl to create the cluster? And when a development version of CAPZ is required, we need to check out the CAPZ repo anyways to be able to build it so it makes sense to reuse the existing makefile targets that are already in the repo.

**Comment by jsturtevant** [comment]
Thanks @CecileRobertMichon. I see that now, I also thought this was going into `cluster-api-provider-azure` (miss read the repo in the url).  Sorry about the confusion :facepalm:

**Comment by nilo19** [comment]
> Thanks @CecileRobertMichon. I see that now, I also thought this was going into `cluster-api-provider-azure` (miss read the repo in the url). Sorry about the confusion 🤦

They do look alike.

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request merged**
