### PR TITLE
test: update pause-win image to the new one k8s.gcr.io/pause:3.4.1

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

As part of the efforts described in this Issue: https://github.com/kubernetes/k8s.io/issues/1525 we are trying to move away from `gcp project gke-release`

Also the pause image was release with windows support as we can see in the merged or in k/k https://github.com/kubernetes/kubernetes/pull/98205

/assign @spiffxp @feiskyer

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
/sig cloud-provider
/provider azure
/sig windows
/wg k8s-infra
/cc @pacoxu @claudiubelu 
FYI, since you've been involved with the pause image change

**Review by spiffxp — APPROVED** [review]
/lgtm

**Comment by spiffxp** [comment]
/assign @feiskyer @andyzhangx 
for the /approve

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Review by pacoxu — APPROVED** [review]

**Pull request merged**
