### PR TITLE
feat: add blobclient for blob container operations

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
feat: add blobclient for blob container operations

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
feat: add blobclient for blob container operations
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
feat: add blobclient for blob container operations
```

### CODE REVIEW

**Review by ZeroMagic — APPROVED** [review]
/lgtm

**Comment by andyzhangx** [comment]
cc @lzhecheng there are quite a few e2e tests are failing frequently.

**Comment by nilo19** [comment]
can we unit test this one?

**Comment by andyzhangx** [comment]
> can we unit test this one?

@nilo19 done, PTAL.

**Comment by nilo19** [comment]
> > can we unit test this one?
> 
> @nilo19 done, PTAL.

thanks, please squash the commits.

**Comment by andyzhangx** [comment]
> > > can we unit test this one?
> > 
> > 
> > @nilo19 done, PTAL.
> 
> thanks, please squash the commits.

@nilo19 is it necessary to squash the two commits 1) feature code 2) unit test? I think it's usually ok to have commits with one feature code commit and test commit

**Pull request merged**
