### PR TITLE
fix: k8s 1.31 condition

### PR DESCRIPTION
**Pull request by mweibel**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
cloud-provider-azure helm chart doesn't work for 1.31 based clusters because of a wrong condition.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by mweibel** [comment]
FYI @mboersma - original change was in #6938

**Review by mboersma — APPROVED** [review]
/lgtm

🤦🏻

**Comment by mweibel** [comment]
> /lgtm
> 
> 🤦🏻

:smile: happens :)

**Comment by mboersma** [comment]
Actually I spoke too soon. Any change to the Helm chart requires a new chart release.

So we need to bump `version` to `v1.31.1` in Chart.yaml, update `cloudProviderAzureVersion`s in cloud-provider-azure.yaml to the current patches, and run `make update-helm`.

Let me know if I can help with any of that. Thanks for noticing this! Sorry for the braindead copy-paste. 😄

**Comment by mweibel** [comment]
thanks for the pointers - just updated! Let me know if there's anything else I need to check.

**Comment by mweibel** [comment]
found a few more version updates - hope that's all now.

**Comment by mweibel** [comment]
I think the /ok-to-test is already applied but would need an /approve now if all is fine.

**Pull request merged**
