### PR TITLE
Remove feature gate MixedProtocolLBService

### PR DESCRIPTION
**Pull request by lzhecheng**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Remove feature gate MixedProtocolLBService
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/#feature-gates-that-are-removed

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Review by Chiefy0x1 — COMMENTED** [review]
/test all

**Comment by lzhecheng** [comment]
The failure is not related to the change.

**Pull request merged**
