### PR TITLE
[E2E][VMSS Flex] Add a customized cloud provider config

### PR DESCRIPTION
**Pull request by zmyzheng**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR adds a customized cloud provider config for VMSS Flex E2E testing

#### Which issue(s) this PR fixes:

Refer to #2731 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
Is it possible to reuse the existing json?

**Comment by zmyzheng** [comment]
> Is it possible to reuse the existing json?

I need to add a new field: "enableVmssFlexNodes": true
In this case, how to reuse the eixting json?

**Comment by nilo19** [comment]
> > Is it possible to reuse the existing json?
> 
> I need to add a new field: "enableVmssFlexNodes": true In this case, how to reuse the eixting json?

Append it to the existing one, using an environment variable to control.

**Comment by zmyzheng** [comment]
> > > Is it possible to reuse the existing json?
> > 
> > 
> > I need to add a new field: "enableVmssFlexNodes": true In this case, how to reuse the eixting json?
> 
> Append it to the existing one, using an environment variable to control.

I can add it to the json file you created before, but that will break your existing pipeline as your existing pipeline does not have the env variable of enableVmssFlexNodes

**Comment by nilo19** [comment]
> > > > Is it possible to reuse the existing json?
> > > 
> > > 
> > > I need to add a new field: "enableVmssFlexNodes": true In this case, how to reuse the eixting json?
> > 
> > 
> > Append it to the existing one, using an environment variable to control.
> 
> I can add it to the json file you created before, but that will break your existing pipeline as your existing pipeline does not have the env variable of enableVmssFlexNodes

Can you add it for https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L194?

**Comment by zmyzheng** [comment]
> > > > > Is it possible to reuse the existing json?
> > > > 
> > > > 
> > > > I need to add a new field: "enableVmssFlexNodes": true In this case, how to reuse the eixting json?
> > > 
> > > 
> > > Append it to the existing one, using an environment variable to control.
> > 
> > 
> > I can add it to the json file you created before, but that will break your existing pipeline as your existing pipeline does not have the env variable of enableVmssFlexNodes
> 
> Can you add it for https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L194?

Sure, here is the PR: https://github.com/kubernetes/test-infra/pull/27969. Can you approve it?

**Pull request merged**
