### PR TITLE
Cherry-pick #607, #627 and #841 to branch release-0.7

### PR DESCRIPTION
**Pull request by lzhecheng**
#### What this PR does / why we need it:
Cherry-pick #607, #627 and #841 to branch release-0.7 to solve flaky tests.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Cherry-pick #607 to solve flaky tests:
* should add all nodes in different agent pools to backends [MultipleAgentPools]: fail to find `backendAddressPoolID` in `lbBackendAddressPoolsIDMap`
* Found no or more than 1 virtual network in resource group same as cluster name
* cannot obtain the master node

Failures e.g.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/969/pull-cloud-provider-azure-e2e-ccm-capz-1-20/1479028839588827136

Cherry-pick #627 to solve "get outbound rules" issue
Cherry-pick #841 to solve "not equal 0" issue

Failures e.g.
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/982/pull-cloud-provider-azure-e2e-ccm-capz-1-20/1480370475220602880
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lzhecheng** [comment]
@nilo19 please help ok-to-test

**Comment by feiskyer** [comment]
Could you add a release note in the PR description part (inside release note part):

```
```release-note

```

**Comment by lzhecheng** [comment]
This time only 2 tests in `pull-cloud-provider-azure-e2e-ccm-capz-1-20` failed:
* should make outbound IP of pod same as in SLB's outbound rules: outbound rule number should not equal 0
* should support updating internal IP when updating internal service: WaitServiceExposure() timeout

Added 2 fix commits and trigger the test again.

**Pull request merged**
