### PR TITLE
test: update CAPZ test templates to include calico HelmChartProxy

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR adds an appropriate calico `HelmChartProxy` resource spec for each custom CAPZ cluster template used by cloud-provider-azure test scenarios. This addition is to fulfill a new CAPZ `ci-entrypoint.sh` requirement to include the calico helm spec as a declarative `HelmChartProxy` resource. `ci-entrypoint.sh` no longer automatically installs calico manually by shelling out to the helm CLI as of CAPZ v1.12.0.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
/hold

This PR needs to merge first: https://github.com/kubernetes/test-infra/pull/31320

**Comment by lzhecheng** [comment]
How about csi-driver part? I see it in capz template along with calico part.

**Pull request merged**
