### PR TITLE
[release-1.25] fix: remove deleted node IP address from IP-based LB backend pools

### PR DESCRIPTION
**Pull request by nilo19**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

We should remove deleted node IPs from the IP-based backend pools.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
fix: remove deleted node IP address from IP-based LB backend pools
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lzhecheng** [comment]
Is this duplicate with https://github.com/kubernetes-sigs/cloud-provider-azure/pull/4150?

**Comment by lzhecheng** [comment]
/unhold
Got it. This PR is for 1.25. The other one is for 1.24 but the title is incorrect.

**Comment by nilo19** [comment]
> Is this duplicate with #4150?

No, that one is for v1.24, but I set the wrong title.

**Pull request merged**
