### PR TITLE
Bump Helm chart to v1.28.1

### LINKED ISSUE #4696: Helm Chart v1.28.1 not pushed to repo
#### What happened:
Tried to install v1.28.1 via Helm

#### What you expected to happen:
Install of Helm chart v1.28.1

#### How to reproduce it (as minimally and precisely as possible):

```
$ helm repo add azure https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo
$ helm repo update
$ helm search repo azure
NAME                                            CHART VERSION   APP VERSION     DESCRIPTION
azure/cloud-provider-azure                  1.28.0                          A Helm chart for installing kubernetes-sigs/clo...
```

#### Environment:

Helm: v3.12.0

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes #4696 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/assign @jackfrancis @lzhecheng

**Comment by jackfrancis** [comment]
/lgtm

(hopefully codespell errors aren't blocking)

**Comment by lzhecheng** [comment]
LGTM
The codespell failed and it should be resolved in another PR.

**Comment by lzhecheng** [comment]
@CecileRobertMichon could you rebase the PR? The typo fix has been merged.

**Pull request merged**
