### PR TITLE
Refactor: Use armclient functions

### PR DESCRIPTION
**Pull request by lzhecheng**
Add a new function GetResourceListID() and use other armclient ones if possible.

Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Add a new function GetResourceListID() and use other armclient ones if possible.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MartinForReal** [comment]
I'm wondering if it feasible to split the commit and replace commit message with meaningful content.

**Comment by lzhecheng** [comment]
> I'm wondering if it feasible to split the commit and replace commit message with meaningful content.

I put them together because there's no big code change. What's your sugested way?
I updated the commit message.

**Comment by MartinForReal** [comment]
It's a bit messy if we need to backport it. Maybe we can split it into five commits. 
Add armclient.GetResourceListID()
Use expand variable to query if needed
Remove unneeded api version change
Use variables for resource type strings
Use GetThrottlingError and GetRateLimitError

Any ideas?

**Pull request merged**
