### PR TITLE
fix: detach disk panic on Azure Stack

### LINKED ISSUE #684: AzureStackHub: panic: runtime error: slice bounds out of range
Hey there, I'm currently working on getting OpenShift 4.9 running on Azure StackHub. We already have a test cluster running and I'm currently looking into running the [azure-disk-csi-driver-controller](https://github.com/kubernetes-sigs/azuredisk-csi-driver) and making sure all e2e tests in the [CSI suite](https://github.com/kubernetes/kubernetes/blob/588d98440706e317ca0fcc5b510285caaf161e51/test/e2e/storage/framework/testpattern.go) pass.

**What happened**:

On some tests (especially the multivolume ones), the driver dies with the following panic:

```go
I0629 14:07:35.520114       1 utils.go:96] GRPC request: {"volume_id":"/subscriptions/e90a4bc2-2f4e-4d36-874b-9011e4734d74/resourceGroups/padillon-7xkrc-rg/providers/Microsoft.Compute/disks/pvc-1ecb4793-f484-4914-821d-bbee3164fed9"}
I0629 14:07:35.520201       1 controllerserver.go:349] deleting azure disk(/subscriptions/e90a4bc2-2f4e-4d36-874b-9011e4734d74/resourceGroups/padillon-7xkrc-rg/providers/Microsoft.Compute/disks/pvc-1ecb4793-f484-4914-821d-bbee3164fed9)
I0629 14:07:35.535709       1 utils.go:95] GRPC call: /csi.v1.Controller/DeleteVolume
I0629 14:07:35.535727       1 utils.go:96] GRPC request: {"volume_id":"/subscriptions/e90a4bc2-2f4e-4d36-874b-9011e4734d74/resourceGroups/padillon-7xkrc-rg/providers/Microsoft.Compute/disks/pvc-8c4595fd-d372-4d45-9026-1e2b4fc5b7bc"}
I0629 14:07:35.535812       1 controllerserver.go:349] deleting azure disk(/subscriptions/e90a4bc2-2f4e-4d36-874b-9011e4734d74/resourceGroups/padillon-7xkrc-rg/providers/Microsoft.Compute/disks/pvc-8c4595fd-d372-4d45-9026-1e2b4fc5b7bc)
I0629 14:07:35.577065       1 controllerserver.go:351] delete azure disk(/subscriptions/e90a4bc2-2f4e-4d36-874b-9011e4734d74/resourceGroups/padillon-7xkrc-rg/providers/Microsoft.Compute/disks/pvc-1ecb4793-f484-4914-821d-bbee3164fed9) returned with Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/disks/pvc-1ecb4793-f484-4914-821d-bbee3164fed9' under resource group 'padillon-7xkrc-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
E0629 14:07:35.577092       1 utils.go:100] GRPC error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Compute/disks/pvc-1ecb4793-f484-4914-821d-bbee3164fed9' under resource group 'padillon-7xkrc-rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
I0629 14:07:35.590553       1 azure_controller_standard.go:159] azureDisk - detach disk: name "pvc-b3e2278e-e8a7-450f-beed-bd65a40634e2" uri "/subscriptions/e90a4bc2-2f4e-4d36-874b-9011e4734d74/resourcegroups/padillon-7xkrc-rg/providers/microsoft.compute/disks/pvc-b3e2278e-e8a7-450f-beed-bd65a40634e2"
I0629 14:07:35.590581       1 azure_controller_standard.go:159] azureDisk - detach disk: name "pvc-6c570f18-08df-46a0-a471-6c8bb12dcbd0" uri "/subscriptions/e90a4bc2-2f4e-4d36-874b-9011e4734d74/resourcegroups/padillon-7xkrc-rg/providers/microsoft.compute/disks/pvc-6c570f18-08df-46a0-a471-6c8bb12dcbd0"
panic: runtime error: slice bounds out of range [2:1]

goroutine 126 [running]:
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*availabilitySet).DetachDisk(0xc000010da0, 0xc00060c570, 0x17, 0xc0003a7530, 0x0, 0x0)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go:161 +0x1916
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*controllerCommon).DetachDisk(0xc000193450, 0xc0003786b7, 0x28, 0xc000378640, 0x9f, 0xc00060c570, 0x17, 0x27, 0xc0003fcce0)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go:309 +0x1386
sigs.k8s.io/azuredisk-csi-driver/pkg/azuredisk.(*Driver).ControllerUnpublishVolume(0xc000120d80, 0x1c8ae58, 0xc000174690, 0xc00003c140, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/azure-disk-csi-driver/pkg/azuredisk/controllerserver.go:468 +0x385
github.com/container-storage-interface/spec/lib/go/csi._Controller_ControllerUnpublishVolume_Handler.func1(0x1c8ae58, 0xc000174690, 0x1959020, 0xc00003c140, 0x0, 0x0, 0x1a57801, 0x10)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5561 +0x89
sigs.k8s.io/azuredisk-csi-driver/pkg/csi-common.logGRPC(0x1c8ae58, 0xc000174690, 0x1959020, 0xc00003c140, 0xc0003fcbc0, 0xc0006a46a8, 0xc000758b80, 0x49cc86, 0x192e0c0, 0xc000174690)
	/go/src/github.com/openshift/azure-disk-csi-driver/pkg/csi-common/utils.go:98 +0x2ab
github.com/container-storage-interface/spec/lib/go/csi._Controller_ControllerUnpublishVolume_Handler(0x1a1c560, 0xc000120d80, 0x1c8ae58, 0xc000174690, 0xc0001abf20, 0x1b17268, 0x1c8ae58, 0xc000174690, 0xc000022b40, 0xbb)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5563 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000602780, 0x1c9e1f8, 0xc00076f080, 0xc000118e00, 0xc000036270, 0x273b128, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000602780, 0x1c9e1f8, 0xc00076f080, 0xc000118e00, 0x0)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:1313 +0xd4c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0001945b0, 0xc000602780, 0x1c9e1f8, 0xc00076f080, 0xc000118e00)
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:722 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/openshift/azure-disk-csi-driver/vendor/google.golang.org/grpc/server.go:720 +0xa5

```

I could trace this back to some in-tree code that was added to fix the ASH build here: https://github.com/kubernetes/legacy-cloud-providers/commit/e7d1b0c6c90cba11798462ddfd1b2cf330218149

However I can make very little sense of this in my current azure stackhub setup. There is only a single disk and thus the extra slice logic does not work.

**What you expected to happen**:

I do not expect the driver to panic in that scenario and properly detach the disk.

**How to reproduce it**:

I'm running our [openshift origin e2e tests](https://github.com/openshift/origin) using:

> ./openshift-tests run openshift/csi --run="Dynamic.*multiVolume"

There will be several failures like that:

```
Failing tests:

External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (block volmode)] multiVolume [Slow] should access to two volumes with different volume mode and retain data across pod recreation on different node [LinuxOnly]
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (block volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on different node [LinuxOnly]
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (block volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on the same node [LinuxOnly]
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on different node [LinuxOnly]
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] should access to two volumes with the same volume mode and retain data across pod recreation on the same node [LinuxOnly]
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] should concurrently access the single read-only volume from pods on the same node
External Storage [Driver: disk.csi.azure.com] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] should concurrently access the single volume from pods on the same node [LinuxOnly]
```

Running the tests triggers the above failure conditions.

**Anything else we need to know?**:

We got a ppe3 ASH deployment and we have deployed OpenShift over it, I can share the access if you want to take a closer look. 

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.1-1380+120883fe7ff642-dirty", GitCommit:"120883fe7ff642c7de79ec1e533e4c63cf099eb0", GitTreeState:"dirty", BuildDate:"2021-06-12T07:23:02Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from /etc/os-release):

```
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="47.83.202104131913-0"
VERSION_ID="4.7"
OPENSHIFT_VERSION="4.7"
RHEL_VERSION="8.3"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 47.83.202104131913-0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.7"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.7"
OSTREE_VERSION='47.83.202104131913-0'
```

- Kernel (e.g. `uname -a`): 4.18.0-240.8.1.el8_3.x86_64 #1 SMP Fri Dec 4 12:24:03 EST 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: we installed the driver using our patched operator: https://github.com/openshift/azure-disk-csi-driver-operator/pull/26
- Others:

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: detach disk panic on Azure Stack

e2e tests already passes on https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/909

**Which issue(s) this PR fixes**:

Fixes #684

**Special notes for your reviewer**:

**Release note**:
```
fix: detach disk panic on Azure Stack
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
cc @songjiaxun

**Review by feiskyer — COMMENTED** [review]
Looks good. Could you add some unit tests for the changed logic?

**Comment by andyzhangx** [comment]
> Looks good. Could you add some unit tests for the changed logic?

@feiskyer ut added.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
