### PR TITLE
Skip "instance not found" error for LB backend address pools

### PR DESCRIPTION
**Pull request by lzhecheng**
Signed-off-by: Zhecheng Li <zhechengli@microsoft.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Skip "instance not found" error for LB backend address pools
related: https://github.com/kubernetes/kubernetes/issues/111331
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Skip "instance not found" error for LB backend address pools
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lzhecheng** [comment]
/assign @feiskyer 
cc @ydp

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
