### PR TITLE
Typos fixed in pls-integration.md

### LINKED ISSUE #2132: Typos in PLS integration
It should be `specified` not `specifed`

Screenshot (255)

### PR DESCRIPTION
**Pull request by bishal7679**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

`specifed` is changed into `specified`

## Fixes #2132 

```release-note
   This will fix the typo specifed
```

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

### CODE REVIEW

**Comment by jwtty** [comment]
thanks for fixing!

**Comment by jwtty** [comment]
Hi @bishal7679 , could you pls add a release note (refer PR template)? It's required and is blocking the merge. Thanks

**Comment by bishal7679** [comment]
@jwtty How can I add a release note in this PR now?


__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question&nbsp; | &nbsp;**Tags:** Reusable

**Pull request merged**
